# Convert our Images into Text

In [1]:
import torch
from transformers import AutoProcessor, Blip2ForConditionalGeneration
import torch
import os
import requests
from PIL import Image
from io import BytesIO
from pathlib import Path
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor, as_completed

In [2]:
print(f"CUDA available?: {torch.cuda.is_available()}")
print(f"Device Name: {torch.cuda.get_device_name()}")
device = "cuda:0"
torch.cuda.set_device(device)

CUDA available?: True
Device Name: AMD Radeon RX 9060 XT

<p style="color:red">Task for this notebook</p>

- [ ] comment code and explain (briefly) thought process

## Demo

In [3]:
processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")
model = Blip2ForConditionalGeneration.from_pretrained(
    "Salesforce/blip2-opt-2.7b", 
    dtype=torch.float16
).to(device)

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [4]:
img_url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/pipeline-cat-chonk.jpeg"
image = Image.open(requests.get(img_url, stream=True).raw).convert("RGB")

In [5]:
def generate_caption(image):
    inputs = processor(image, return_tensors="pt").to(device, torch.float16)

    generated_ids = model.generate(**inputs, max_new_tokens=30)
    generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
    
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    
    return generated_text

In [6]:
generate_caption(image)

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/transformers/integrations/sdpa_attention.py:96: UserWarning: Flash Efficient attention on Current AMD GPU is still experimental. Enable it with TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1. (Triggered internally at /pytorch/aten/src/ATen/native/transformers/hip/sdp_utils.cpp:316.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/transformers/integrations/sdpa_attention.py:96: UserWarning: Mem Efficient attention on Current AMD GPU is still experimental. Enable it with TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1. (Triggered internally at /pytorch/aten/src/ATen/native/transformers/hip/sdp_utils.cpp:373.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

'a cat walking on snow in an enclosure'

## Convert Images into Text

### Load Datasets

In [7]:
data_dir = Path("../cleaned")  # change if your data directory is elsewhere

datasets = []

for file_name in data_dir.rglob("*.csv"):
    if file_name.stem.endswith("_images"):
        df = pd.read_csv(str(file_name))
        df._name = file_name.name[:-11]  # or file_name.stem, or str(file_name)
        datasets.append(df)

### Cleaning Datasets

In [8]:
for df in datasets:
    df["subreddit"] = df._name  # Assign subreddit name from file name to each dataframe
    df.drop(columns=["media_id", "image_type", "image_source"], inplace=True) # Drop media_id

KeyError: "['media_id', 'image_type', 'image_source'] not found in axis"

In [9]:
def parse_image(image_url, headers={"User-Agent": "Mozilla/5.0"}):
    resp = requests.get(image_url, headers=headers, timeout=5)
    resp.raise_for_status()
    image = Image.open(BytesIO(resp.content)).convert("RGBA")
    return image

In [10]:
def url_is_ok(url):
    try:
        parse_image(url)
        return True
    except Exception:
        return False

In [13]:
cpu_count = os.cpu_count() or 4
print("CPU cores:", cpu_count)

# Good starting points for IO-bound (network) work:
max_workers = cpu_count * 5   # or * 10 if your network / API can handle it
print("Suggested max_workers:", max_workers)

CPU cores: 12
Suggested max_workers: 60

In [14]:
cleaned_datasets = []
total_datasets = len(datasets)

for i, df in enumerate(datasets, start=1):
    original_len = len(df)
    bad_idx = []

    # run URL checks in parallel
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_idx = {
            executor.submit(url_is_ok, url): idx
            for idx, url in df["image_url"].items()
        }
        for future in as_completed(future_to_idx):
            idx = future_to_idx[future]
            ok = future.result()
            if not ok:
                bad_idx.append(idx)

    df = df.drop(index=bad_idx)
    cleaned_datasets.append(df)

    removed = len(bad_idx)
    pct_removed = (removed / original_len * 100) if original_len > 0 else 0.0

    print(f"Dataset {i}/{total_datasets}: removed {removed} images "
          f"({pct_removed:.2f}% removed).")
    print(f"Datasets left to filter through: {total_datasets - i}")

Dataset 1/78: removed 1 images (12.50% removed).
Datasets left to filter through: 77
Dataset 2/78: removed 6 images (54.55% removed).
Datasets left to filter through: 76
Dataset 3/78: removed 0 images (0.00% removed).
Datasets left to filter through: 75
Dataset 4/78: removed 14 images (2.97% removed).
Datasets left to filter through: 74
Dataset 5/78: removed 5 images (38.46% removed).
Datasets left to filter through: 73
Dataset 6/78: removed 48 images (6.71% removed).
Datasets left to filter through: 72
Dataset 7/78: removed 0 images (0.00% removed).
Datasets left to filter through: 71
Dataset 8/78: removed 0 images (0.00% removed).
Datasets left to filter through: 70
Dataset 9/78: removed 20 images (9.17% removed).
Datasets left to filter through: 69
Dataset 10/78: removed 3 images (15.79% removed).
Datasets left to filter through: 68
Dataset 11/78: removed 6 images (3.49% removed).
Datasets left to filter through: 67
Dataset 12/78: removed 4 images (40.00% removed).
Datasets left to filter through: 66
Dataset 13/78: removed 7 images (14.58% removed).
Datasets left to filter through: 65
Dataset 14/78: removed 0 images (0.00% removed).
Datasets left to filter through: 64
Dataset 15/78: removed 1 images (0.67% removed).
Datasets left to filter through: 63
Dataset 16/78: removed 29 images (7.36% removed).
Datasets left to filter through: 62
Dataset 17/78: removed 10 images (3.73% removed).
Datasets left to filter through: 61
Dataset 18/78: removed 54 images (7.99% removed).
Datasets left to filter through: 60
Dataset 19/78: removed 38 images (2.99% removed).
Datasets left to filter through: 59
Dataset 20/78: removed 0 images (0.00% removed).
Datasets left to filter through: 58
Dataset 21/78: removed 20 images (10.31% removed).
Datasets left to filter through: 57
Dataset 22/78: removed 3 images (18.75% removed).
Datasets left to filter through: 56
Dataset 23/78: removed 20 images (4.00% removed).
Datasets left to filter through: 55

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (114738774 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

Dataset 24/78: removed 29 images (5.82% removed).
Datasets left to filter through: 54
Dataset 25/78: removed 63 images (22.42% removed).
Datasets left to filter through: 53
Dataset 26/78: removed 1 images (100.00% removed).
Datasets left to filter through: 52
Dataset 27/78: removed 10 images (3.40% removed).
Datasets left to filter through: 51
Dataset 28/78: removed 1 images (14.29% removed).
Datasets left to filter through: 50
Dataset 29/78: removed 12 images (23.08% removed).
Datasets left to filter through: 49
Dataset 30/78: removed 43 images (9.01% removed).
Datasets left to filter through: 48

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (154716504 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

Dataset 31/78: removed 10 images (1.81% removed).
Datasets left to filter through: 47
Dataset 32/78: removed 152 images (26.81% removed).
Datasets left to filter through: 46
Dataset 33/78: removed 5 images (35.71% removed).
Datasets left to filter through: 45

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (96028872 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

Dataset 34/78: removed 16 images (4.42% removed).
Datasets left to filter through: 44
Dataset 35/78: removed 0 images (0.00% removed).
Datasets left to filter through: 43
Dataset 36/78: removed 10 images (26.32% removed).
Datasets left to filter through: 42
Dataset 37/78: removed 34 images (5.64% removed).
Datasets left to filter through: 41
Dataset 38/78: removed 0 images (0.00% removed).
Datasets left to filter through: 40
Dataset 39/78: removed 0 images (0.00% removed).
Datasets left to filter through: 39
Dataset 40/78: removed 12 images (3.93% removed).
Datasets left to filter through: 38
Dataset 41/78: removed 1 images (4.00% removed).
Datasets left to filter through: 37
Dataset 42/78: removed 8 images (1.37% removed).
Datasets left to filter through: 36
Dataset 43/78: removed 87 images (10.85% removed).
Datasets left to filter through: 35
Dataset 44/78: removed 10 images (38.46% removed).
Datasets left to filter through: 34
Dataset 45/78: removed 6 images (3.11% removed).
Datasets left to filter through: 33
Dataset 46/78: removed 24 images (4.89% removed).
Datasets left to filter through: 32
Dataset 47/78: removed 0 images (0.00% removed).
Datasets left to filter through: 31
Dataset 48/78: removed 13 images (1.61% removed).
Datasets left to filter through: 30
Dataset 49/78: removed 3 images (11.54% removed).
Datasets left to filter through: 29
Dataset 50/78: removed 10 images (11.36% removed).
Datasets left to filter through: 28
Dataset 51/78: removed 18 images (3.60% removed).
Datasets left to filter through: 27
Dataset 52/78: removed 11 images (20.00% removed).
Datasets left to filter through: 26
Dataset 53/78: removed 6 images (9.68% removed).
Datasets left to filter through: 25
Dataset 54/78: removed 5 images (10.42% removed).
Datasets left to filter through: 24
Dataset 55/78: removed 0 images (0.00% removed).
Datasets left to filter through: 23
Dataset 56/78: removed 139 images (18.36% removed).
Datasets left to filter through: 22
Dataset 57/78: removed 22 images (15.60% removed).
Datasets left to filter through: 21

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (96000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

Dataset 58/78: removed 18 images (4.00% removed).
Datasets left to filter through: 20
Dataset 59/78: removed 4 images (57.14% removed).
Datasets left to filter through: 19
Dataset 60/78: removed 42 images (13.38% removed).
Datasets left to filter through: 18
Dataset 61/78: removed 1 images (2.33% removed).
Datasets left to filter through: 17
Dataset 62/78: removed 2 images (1.54% removed).
Datasets left to filter through: 16
Dataset 63/78: removed 5 images (4.55% removed).
Datasets left to filter through: 15
Dataset 64/78: removed 4 images (4.21% removed).
Datasets left to filter through: 14
Dataset 65/78: removed 0 images (0.00% removed).
Datasets left to filter through: 13
Dataset 66/78: removed 13 images (2.50% removed).
Datasets left to filter through: 12
Dataset 67/78: removed 98 images (15.93% removed).
Datasets left to filter through: 11
Dataset 68/78: removed 21 images (1.64% removed).
Datasets left to filter through: 10

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (108000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

Dataset 69/78: removed 2 images (1.44% removed).
Datasets left to filter through: 9
Dataset 70/78: removed 41 images (2.45% removed).
Datasets left to filter through: 8

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (96000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (161678160 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

Dataset 71/78: removed 34 images (6.55% removed).
Datasets left to filter through: 7
Dataset 72/78: removed 2 images (0.78% removed).
Datasets left to filter through: 6
Dataset 73/78: removed 1 images (14.29% removed).
Datasets left to filter through: 5
Dataset 74/78: removed 0 images (0.00% removed).
Datasets left to filter through: 4
Dataset 75/78: removed 3 images (3.33% removed).
Datasets left to filter through: 3
Dataset 76/78: removed 5 images (22.73% removed).
Datasets left to filter through: 2
Dataset 77/78: removed 77 images (13.73% removed).
Datasets left to filter through: 1
Dataset 78/78: removed 9 images (1.88% removed).
Datasets left to filter through: 0

### Images -> Text Coversion

In [18]:
cpu_count = os.cpu_count() or 12
max_workers_fetch = cpu_count * 4      # ~48 workers on your CPU
max_workers_caption = 1                # GPU-bound, keep serial

captioned_datasets = []
total_datasets = len(cleaned_datasets)

for i, df in enumerate(cleaned_datasets, start=1):
    captions = {}

    # parallelize: fetch image + caption, small worker count (GPU-bound)
    def fetch_and_caption(idx, url):
        img = parse_image(url)          # network + PIL
        cap = generate_caption(img)     # GPU caption
        return idx, cap

    with ThreadPoolExecutor(max_workers=max_workers_caption) as executor:
        futures = [
            executor.submit(fetch_and_caption, idx, url)
            for idx, url in df["image_url"].items()
        ]

        for future in as_completed(futures):
            try:
                idx, cap = future.result()
            except Exception:
                # if captioning fails, store None (or "" if you prefer)
                idx, cap = None, None
            if idx is not None:
                captions[idx] = cap

    df["caption"] = df.index.map(captions.get)
    captioned_datasets.append(df)

    print(f"[CAPTION] Dataset {i}/{total_datasets} captioned "
          f"({total_datasets - i} datasets left).")

[CAPTION] Dataset 1/78 captioned (77 datasets left).
[CAPTION] Dataset 2/78 captioned (76 datasets left).
[CAPTION] Dataset 3/78 captioned (75 datasets left).
[CAPTION] Dataset 4/78 captioned (74 datasets left).
[CAPTION] Dataset 5/78 captioned (73 datasets left).
[CAPTION] Dataset 6/78 captioned (72 datasets left).
[CAPTION] Dataset 7/78 captioned (71 datasets left).
[CAPTION] Dataset 8/78 captioned (70 datasets left).
[CAPTION] Dataset 9/78 captioned (69 datasets left).
[CAPTION] Dataset 10/78 captioned (68 datasets left).
[CAPTION] Dataset 11/78 captioned (67 datasets left).
[CAPTION] Dataset 12/78 captioned (66 datasets left).
[CAPTION] Dataset 13/78 captioned (65 datasets left).
[CAPTION] Dataset 14/78 captioned (64 datasets left).
[CAPTION] Dataset 15/78 captioned (63 datasets left).
[CAPTION] Dataset 16/78 captioned (62 datasets left).
[CAPTION] Dataset 17/78 captioned (61 datasets left).
[CAPTION] Dataset 18/78 captioned (60 datasets left).
[CAPTION] Dataset 19/78 captioned (59 datasets left).
[CAPTION] Dataset 20/78 captioned (58 datasets left).
[CAPTION] Dataset 21/78 captioned (57 datasets left).
[CAPTION] Dataset 22/78 captioned (56 datasets left).
[CAPTION] Dataset 23/78 captioned (55 datasets left).

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (114738774 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

[CAPTION] Dataset 24/78 captioned (54 datasets left).
[CAPTION] Dataset 25/78 captioned (53 datasets left).
[CAPTION] Dataset 26/78 captioned (52 datasets left).
[CAPTION] Dataset 27/78 captioned (51 datasets left).
[CAPTION] Dataset 28/78 captioned (50 datasets left).
[CAPTION] Dataset 29/78 captioned (49 datasets left).
[CAPTION] Dataset 30/78 captioned (48 datasets left).

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (154716504 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

[CAPTION] Dataset 31/78 captioned (47 datasets left).
[CAPTION] Dataset 32/78 captioned (46 datasets left).
[CAPTION] Dataset 33/78 captioned (45 datasets left).

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (96028872 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

[CAPTION] Dataset 34/78 captioned (44 datasets left).
[CAPTION] Dataset 35/78 captioned (43 datasets left).
[CAPTION] Dataset 36/78 captioned (42 datasets left).
[CAPTION] Dataset 37/78 captioned (41 datasets left).
[CAPTION] Dataset 38/78 captioned (40 datasets left).
[CAPTION] Dataset 39/78 captioned (39 datasets left).
[CAPTION] Dataset 40/78 captioned (38 datasets left).
[CAPTION] Dataset 41/78 captioned (37 datasets left).
[CAPTION] Dataset 42/78 captioned (36 datasets left).
[CAPTION] Dataset 43/78 captioned (35 datasets left).
[CAPTION] Dataset 44/78 captioned (34 datasets left).
[CAPTION] Dataset 45/78 captioned (33 datasets left).

The channel dimension is ambiguous. Got image shape (1, 1, 3). Assuming channels are the first dimension. Use the [input_data_format](https://huggingface.co/docs/transformers/main/internal/image_processing_utils#transformers.image_transforms.rescale.input_data_format) parameter to assign the channel dimension.

[CAPTION] Dataset 46/78 captioned (32 datasets left).
[CAPTION] Dataset 47/78 captioned (31 datasets left).
[CAPTION] Dataset 48/78 captioned (30 datasets left).
[CAPTION] Dataset 49/78 captioned (29 datasets left).
[CAPTION] Dataset 50/78 captioned (28 datasets left).
[CAPTION] Dataset 51/78 captioned (27 datasets left).
[CAPTION] Dataset 52/78 captioned (26 datasets left).
[CAPTION] Dataset 53/78 captioned (25 datasets left).
[CAPTION] Dataset 54/78 captioned (24 datasets left).
[CAPTION] Dataset 55/78 captioned (23 datasets left).
[CAPTION] Dataset 56/78 captioned (22 datasets left).
[CAPTION] Dataset 57/78 captioned (21 datasets left).

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (96000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

[CAPTION] Dataset 58/78 captioned (20 datasets left).
[CAPTION] Dataset 59/78 captioned (19 datasets left).
[CAPTION] Dataset 60/78 captioned (18 datasets left).
[CAPTION] Dataset 61/78 captioned (17 datasets left).
[CAPTION] Dataset 62/78 captioned (16 datasets left).
[CAPTION] Dataset 63/78 captioned (15 datasets left).
[CAPTION] Dataset 64/78 captioned (14 datasets left).
[CAPTION] Dataset 65/78 captioned (13 datasets left).
[CAPTION] Dataset 66/78 captioned (12 datasets left).
[CAPTION] Dataset 67/78 captioned (11 datasets left).
[CAPTION] Dataset 68/78 captioned (10 datasets left).

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (108000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

[CAPTION] Dataset 69/78 captioned (9 datasets left).
[CAPTION] Dataset 70/78 captioned (8 datasets left).

/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (161678160 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
/home/maharshii/miniconda3/envs/mlgeneral/lib/python3.10/site-packages/PIL/Image.py:3432: DecompressionBombWarning: Image size (96000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

[CAPTION] Dataset 71/78 captioned (7 datasets left).
[CAPTION] Dataset 72/78 captioned (6 datasets left).
[CAPTION] Dataset 73/78 captioned (5 datasets left).
[CAPTION] Dataset 74/78 captioned (4 datasets left).
[CAPTION] Dataset 75/78 captioned (3 datasets left).
[CAPTION] Dataset 76/78 captioned (2 datasets left).
[CAPTION] Dataset 77/78 captioned (1 datasets left).
[CAPTION] Dataset 78/78 captioned (0 datasets left).

### Save Data Locally

In [34]:
data_dir = Path("../data")

csv_files = [
    str(file_name)[:8] + "cleaned/" + str(file_name)[8:] for file_name in data_dir.rglob("*.csv")
    if file_name.stem.endswith("_images")
]

In [ ]:
for df in datasets:
    df.to_csv(f"../cleaned/{df._name}_images.csv", index=False)
    print(f"Saved: ../cleaned/{df._name}_images.csv")

Saved: ../data/cleaned/sports_images.csv
Saved: ../data/cleaned/maybemaybemaybe_images.csv
Saved: ../data/cleaned/EatCheapAndHealthy_images.csv
Saved: ../data/cleaned/HistoryMemes_images.csv
Saved: ../data/cleaned/videos_images.csv
Saved: ../data/cleaned/pics_images.csv
Saved: ../data/cleaned/books_images.csv
Saved: ../data/cleaned/Jokes_images.csv
Saved: ../data/cleaned/Bitcoin_images.csv
Saved: ../data/cleaned/Showerthoughts_images.csv
Saved: ../data/cleaned/oddlysatisfying_images.csv
Saved: ../data/cleaned/history_images.csv
Saved: ../data/cleaned/cars_images.csv
Saved: ../data/cleaned/PremierLeague_images.csv
Saved: ../data/cleaned/StockMarket_images.csv
Saved: ../data/cleaned/Daytrading_images.csv
Saved: ../data/cleaned/MadeMeSmile_images.csv
Saved: ../data/cleaned/mildlyinfuriating_images.csv
Saved: ../data/cleaned/ThriftStoreHauls_images.csv
Saved: ../data/cleaned/dadjokes_images.csv
Saved: ../data/cleaned/foodhacks_images.csv
Saved: ../data/cleaned/unitedkingdom_images.csv
Saved: ../data/cleaned/RelationshipMemes_images.csv
Saved: ../data/cleaned/Art_images.csv
Saved: ../data/cleaned/IAmA_images.csv
Saved: ../data/cleaned/Entrepreneur_images.csv
Saved: ../data/cleaned/space_images.csv
Saved: ../data/cleaned/worldnews_images.csv
Saved: ../data/cleaned/indieheads_images.csv
Saved: ../data/cleaned/memes_images.csv
Saved: ../data/cleaned/backpacking_images.csv
Saved: ../data/cleaned/SkincareAddiction_images.csv
Saved: ../data/cleaned/news_images.csv
Saved: ../data/cleaned/boardgames_images.csv
Saved: ../data/cleaned/psychology_images.csv
Saved: ../data/cleaned/todayilearned_images.csv
Saved: ../data/cleaned/gifs_images.csv
Saved: ../data/cleaned/Futurology_images.csv
Saved: ../data/cleaned/strength_training_images.csv
Saved: ../data/cleaned/funny_images.csv
Saved: ../data/cleaned/NetflixBestOf_images.csv
Saved: ../data/cleaned/15minutefood_images.csv
Saved: ../data/cleaned/aww_images.csv
Saved: ../data/cleaned/Fitness_images.csv
Saved: ../data/cleaned/Unexpected_images.csv
Saved: ../data/cleaned/Steam_images.csv
Saved: ../data/cleaned/philosophy_images.csv
Saved: ../data/cleaned/BikiniBottomTwitter_images.csv
Saved: ../data/cleaned/gadgets_images.csv
Saved: ../data/cleaned/PS5_images.csv
Saved: ../data/cleaned/itookapicture_images.csv
Saved: ../data/cleaned/HumansBeingBros_images.csv
Saved: ../data/cleaned/WatchPeopleDieInside_images.csv
Saved: ../data/cleaned/movies_images.csv
Saved: ../data/cleaned/AskReddit_images.csv
Saved: ../data/cleaned/MakeupAddiction_images.csv
Saved: ../data/cleaned/math_images.csv
Saved: ../data/cleaned/AnimalsBeingBros_images.csv
Saved: ../data/cleaned/science_images.csv
Saved: ../data/cleaned/iphone_images.csv
Saved: ../data/cleaned/Music_images.csv
Saved: ../data/cleaned/Survival_images.csv
Saved: ../data/cleaned/NintendoSwitch_images.csv
Saved: ../data/cleaned/tifu_images.csv
Saved: ../data/cleaned/LifeProTips_images.csv
Saved: ../data/cleaned/facepalm_images.csv
Saved: ../data/cleaned/DIY_images.csv
Saved: ../data/cleaned/ExpectationVsReality_images.csv
Saved: ../data/cleaned/gaming_images.csv
Saved: ../data/cleaned/anime_irl_images.csv
Saved: ../data/cleaned/EarthPorn_images.csv
Saved: ../data/cleaned/GetMotivated_images.csv
Saved: ../data/cleaned/pettyrevenge_images.csv
Saved: ../data/cleaned/WesternU_images.csv
Saved: ../data/cleaned/europe_images.csv
Saved: ../data/cleaned/explainlikeimfive_images.csv
Saved: ../data/cleaned/ChatGPT_images.csv
Saved: ../data/cleaned/marvelstudios_images.csv

### Merge Content into Original

In [8]:
for df in datasets:
    df["caption"] = "\nImage Description: " + df["caption"]

In [9]:
original_dir = Path("../data")  # change if your data directory is elsewhere
images_dir = datasets  # Path("../cleaned")

datasets_posts = {}
datasets_comments = {}

for file_name in original_dir.rglob("*.csv"):
    if file_name.stem.endswith("_posts"):
        df = pd.read_csv(str(file_name))
        datasets_posts[file_name.stem[:-6]] = df
    elif file_name.stem.endswith("_comments"):
        df = pd.read_csv(str(file_name))
        datasets_comments[file_name.stem[:-9]] = df

In [10]:
images_dir[0]

,subreddit,post_id,comment_id,image_index,image_url,caption
0,sports,1nn83c1,nfs6rbs,0,https://i.imgur.com/fEiAnK9.png,\nImage Description: a table with the names of...
1,sports,1nhmlbz,ned802x,0,https://i.redd.it/zzvcc5ox6qsy.jpg,\nImage Description: the office is a great show
2,sports,1n4dwk2,nblb7ty,0,https://i.imgur.com/CKp1Rup.png)...,\nImage Description: a computer screen showing...
3,sports,1n4dwk2,nblv56f,0,https://i.imgur.com/KriiYZS.png).,\nImage Description: a video game screen showi...
4,sports,1mymugi,naj7o7o,0,https://i.imgur.com/UpPrvIp.jpeg),\nImage Description: a black and white photo o...
5,sports,1mn7qem,n865828,0,https://i.imgur.com/S0eSAh6.gif),\nImage Description: a man with a caption that...
6,sports,1mjdw6b,n7b37iz,0,https://i.imgur.com/HJ1lIFs.png,\nImage Description: a man laying in bed with ...

In [11]:
datasets_posts["funny"]

,subreddit,post_id,post_title,post_score,post_url,post_content_url,post_text,timestamp,post_upvote_ratio,post_ups,post_total_awards_received,post_link_flair_text,post_author,post_num_comments,has_images,num_images,is_gallery,content_type
0,funny,160kuuf,] REMINDER] ANY political content will earn an...,697,https://reddit.com/r/funny/comments/160kuuf/re...,https://www.reddit.com/r/funny/comments/160kuu...,NaN,1.692927e+09,0.95,697,0,[Meta],funny_mod,1,False,0,False,text
1,funny,1npe17w,How did she miss?🤣,3423,https://reddit.com/r/funny/comments/1npe17w/ho...,https://v.redd.it/pm8xc67jk4rf1,NaN,1.758725e+09,0.94,3423,0,NaN,Master-Lunch3644,49,False,0,False,text
2,funny,1npcopx,One of the oddest movie trilogies of recent ti...,1727,https://reddit.com/r/funny/comments/1npcopx/on...,https://i.redd.it/l3a36lgza4rf1.jpeg,NaN,1.758722e+09,0.95,1727,0,NaN,IceBone,75,True,1,False,image
3,funny,1npgsd3,What are these exercises called?,1024,https://reddit.com/r/funny/comments/1npgsd3/wh...,https://v.redd.it/j7ftr5yx25rf1,NaN,1.758731e+09,0.93,1024,0,NaN,CakeFit7690,421,False,0,False,text
4,funny,1np8qxl,EA I WANT A REFUND NOW 🤣,2530,https://reddit.com/r/funny/comments/1np8qxl/ea...,https://v.redd.it/54sc4utzc3rf1,NaN,1.758710e+09,0.92,2530,0,NaN,Current-Assignment7,91,False,0,False,text
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,funny,1najlhy,kidney dance,266,https://reddit.com/r/funny/comments/1najlhy/ki...,https://v.redd.it/wlpltill3onf1,NaN,1.757218e+09,0.85,266,0,NaN,saifmahmud_,22,False,0,False,text
496,funny,1na71ys,Magnificent Toilet Experience....,1285,https://reddit.com/r/funny/comments/1na71ys/ma...,https://v.redd.it/4hieznqw8lnf1,NaN,1.757184e+09,0.76,1285,0,NaN,ZenKenShin,4,False,0,False,text
497,funny,1nauzx5,They set out the special donuts,31,https://reddit.com/r/funny/comments/1nauzx5/th...,https://i.redd.it/gmocbbhw8rnf1.jpeg,NaN,1.757256e+09,0.62,31,0,NaN,ColdH8WarmBlood,17,True,1,False,image
498,funny,1nbzz2z,Does she?,0,https://reddit.com/r/funny/comments/1nbzz2z/do...,https://i.redd.it/9a6f4mspa0of1.jpeg,NaN,1.757366e+09,0.44,0,0,NaN,TheRealBrandon2020,17,True,1,False,image
499,funny,1n9yobt,How's that possible? 🤔 😆,3645,https://reddit.com/r/funny/comments/1n9yobt/ho...,https://v.redd.it/uxwz3b25jjnf1,NaN,1.757163e+09,0.95,3645,0,NaN,Kvnq_Stormy,474,False,0,False,text

In [23]:
datasets_comments["funny"]

,post_id,comment_id,comment_text,comment_score,comment_author,comment_created_utc,parent_id,reply_to_id,comment_sentiment,has_images,num_images,image_urls,subreddit
0,160kuuf,jxmw8th,--- \n>✨⭐ **Don't miss [our 50-million-su...,1,AutoModerator,1.692927e+09,t3_160kuuf,160kuuf,NaN,False,0,NaN,funny
1,1npe17w,nfyf40y,--- \n\n>This is a friendly reminder to [...,1,AutoModerator,1.758725e+09,t3_1npe17w,1npe17w,NaN,False,0,NaN,funny
2,1npe17w,nfyg5gk,Malcolm would be impressed.,128,TheBleeter,1.758725e+09,t3_1npe17w,1npe17w,NaN,False,0,NaN,funny
3,1npe17w,nfytjnm,https://youtu.be/w199OAIBnA0,22,Choz,1.758729e+09,t1_nfyg5gk,nfyg5gk,NaN,False,0,NaN,funny
4,1npe17w,nfyiaoe,Here’s your damn strike!,29,Worldfriend,1.758726e+09,t1_nfyg5gk,nfyg5gk,NaN,False,0,NaN,funny
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12260,1n9yobt,ncq406a,Not gonna lie lol 😆,9,Kvnq_Stormy,1.757163e+09,t1_ncq3n0v,ncq3n0v,NaN,False,0,NaN,funny
12261,1n9yobt,nd5l5df,I wish i could post that hype gif that everyon...,1,locofspades,1.757366e+09,t1_ncq3n0v,ncq3n0v,NaN,False,0,NaN,funny
12262,1n9yobt,nct9roy,"Other cat was like “oh shit, a ghost.”",1,The_Amazing_Emu,1.757200e+09,t1_ncq3n0v,ncq3n0v,NaN,False,0,NaN,funny
12263,1n9yobt,ncsg3bs,I am also amazed by this. Never seen this before.,0,SilentFX,1.757190e+09,t1_ncq3n0v,ncq3n0v,NaN,False,0,NaN,funny
12264,1n9yobt,ncsvzrv,"Could feel the ""bro, whaaat?"" from here.",0,xstrike0,1.757195e+09,t1_ncq3n0v,ncq3n0v,NaN,False,0,NaN,funny

In [12]:
for df in images_dir:
    if 'comment_id' not in df.columns:
        df['comment_id'] = None

In [13]:
# Merge captions from images_dir back into original posts and comments
for img_df in images_dir:
    subreddit_name = img_df._name
    print(f"Merging captions for subreddit: {subreddit_name}")
    
    # Get post captions (where post_id is not null and comment_id is null)
    post_images = img_df[img_df['post_id'].notna() & img_df['comment_id'].isna()].copy()
    
    # Get comment captions (where comment_id is not null)
    comment_images = img_df[img_df['comment_id'].notna()].copy()
    
    # Merge post captions into posts dataframe
    if subreddit_name in datasets_posts and len(post_images) > 0:
        # Group captions by post_id (in case multiple images per post)
        post_captions = post_images.groupby('post_id')['caption'].apply(
            lambda x: ' '.join(x.dropna().astype(str))
        ).reset_index()
        post_captions.columns = ['post_id', 'image_captions']
        
        # Merge into posts
        datasets_posts[subreddit_name] = datasets_posts[subreddit_name].merge(
            post_captions, on='post_id', how='left'
        )
        
        # Append captions to post_text where available
        mask = datasets_posts[subreddit_name]['image_captions'].notna()
        datasets_posts[subreddit_name].loc[mask, 'post_text'] = (
            datasets_posts[subreddit_name].loc[mask, 'post_text'].fillna('') + 
            datasets_posts[subreddit_name].loc[mask, 'image_captions']
        )
        
        # Drop the temporary column
        datasets_posts[subreddit_name].drop(columns=['image_captions'], inplace=True)
        
        print(f"✓ Merged {len(post_captions)} post captions into {subreddit_name}_posts")
    
    # Merge comment captions into comments dataframe
    if subreddit_name in datasets_comments and len(comment_images) > 0:
        # Group captions by comment_id (in case multiple images per comment)
        comment_captions = comment_images.groupby('comment_id')['caption'].apply(
            lambda x: ' '.join(x.dropna().astype(str))
        ).reset_index()
        comment_captions.columns = ['comment_id', 'image_captions']
        
        # Merge into comments
        datasets_comments[subreddit_name] = datasets_comments[subreddit_name].merge(
            comment_captions, on='comment_id', how='left'
        )
        
        # Append captions to comment_text where available
        mask = datasets_comments[subreddit_name]['image_captions'].notna()
        datasets_comments[subreddit_name].loc[mask, 'comment_text'] = (
            datasets_comments[subreddit_name].loc[mask, 'comment_text'].fillna('') + 
            datasets_comments[subreddit_name].loc[mask, 'image_captions']
        )
        
        # Drop the temporary column
        datasets_comments[subreddit_name].drop(columns=['image_captions'], inplace=True)
        
        print(f"✓ Merged {len(comment_captions)} comment captions into {subreddit_name}_comments")

print("\n✅ All captions merged successfully!")

Merging captions for subreddit: sports
✓ Merged 7 comment captions into sports_comments
Merging captions for subreddit: maybemaybemaybe
✓ Merged 4 comment captions into maybemaybemaybe_comments
Merging captions for subreddit: EatCheapAndHealthy
✓ Merged 1 post captions into EatCheapAndHealthy_posts
Merging captions for subreddit: HistoryMemes
✓ Merged 448 post captions into HistoryMemes_posts
✓ Merged 9 comment captions into HistoryMemes_comments
Merging captions for subreddit: videos
✓ Merged 8 comment captions into videos_comments
Merging captions for subreddit: pics
✓ Merged 450 post captions into pics_posts
✓ Merged 7 comment captions into pics_comments
Merging captions for subreddit: books
✓ Merged 1 post captions into books_posts
Merging captions for subreddit: Jokes
✓ Merged 1 comment captions into Jokes_comments
Merging captions for subreddit: Bitcoin
✓ Merged 184 post captions into Bitcoin_posts
Merging captions for subreddit: Showerthoughts
✓ Merged 16 comment captions into Showerthoughts_comments
Merging captions for subreddit: oddlysatisfying
✓ Merged 112 post captions into oddlysatisfying_posts
✓ Merged 10 comment captions into oddlysatisfying_comments
Merging captions for subreddit: history
✓ Merged 4 comment captions into history_comments
Merging captions for subreddit: cars
✓ Merged 29 comment captions into cars_comments
Merging captions for subreddit: PremierLeague
✓ Merged 13 post captions into PremierLeague_posts
Merging captions for subreddit: StockMarket
✓ Merged 111 post captions into StockMarket_posts
✓ Merged 4 comment captions into StockMarket_comments
Merging captions for subreddit: Daytrading
✓ Merged 173 post captions into Daytrading_posts
✓ Merged 63 comment captions into Daytrading_comments
Merging captions for subreddit: MadeMeSmile
✓ Merged 167 post captions into MadeMeSmile_posts
✓ Merged 2 comment captions into MadeMeSmile_comments
Merging captions for subreddit: mildlyinfuriating
✓ Merged 352 post captions into mildlyinfuriating_posts
✓ Merged 179 comment captions into mildlyinfuriating_comments
Merging captions for subreddit: ThriftStoreHauls
✓ Merged 475 post captions into ThriftStoreHauls_posts
✓ Merged 79 comment captions into ThriftStoreHauls_comments
Merging captions for subreddit: dadjokes

/tmp/ipykernel_54516/2090079016.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['\nImage Description: a collage of pictures of a woman on a motorcycle, a dog and a truck'
 '\nImage Description: a man in uniform giving a speech at a podium'
 '\nImage Description: president trump and his staff pose for a photo in the oval office \nImage Description: president donald trump shakes hands with students at the white house \nImage Description: president donald trump with students at the white house \nImage Description: a group of young men holding an american flag'
 '\nImage Description: a black and white photo of three men and a woman'
 '\nImage Description: a man stands in the middle of a hole in the ground'
 '\nImage Description: a man is riding a bike in front of a building'
 '\nImage Description: a woman wearing a colorful scarf taking a selfie'
 '\nImage Description: an old black and white photo of a woman in uniform'
 '\nImage Description: a man standing on the beach with a surfboard \nImage Description: a man on a surfboard in the ocean \nImage Description: a man standing on the beach holding a surfboard \nImage Description: a man standing on the beach holding a surfboard at night'
 '\nImage Description: the usb charger is attached to the wall outlet'
 '\nImage Description: a truck driving down the road with a sign on it'
 '\nImage Description: donald trump is looking at the camera in a suit and tie'
 '\nImage Description: president donald trump in the oval office'
 '\nImage Description: a group of men posing with an american flag'
 '\nImage Description: a man standing on top of a plane with a sign on it'
 '\nImage Description: president donald trump delivers his speech at the un general assembly'
 '\nImage Description: two statues of two men holding hands in front of the washington monument \nImage Description: a plaque on a pedestal \nImage Description: in honor of friendship month \nImage Description: donald j trump statue in washington, dc \nImage Description: two statues of two men holding hands \nImage Description: two statues of two men holding hands in front of the capitol building'
 '\nImage Description: a white truck parked next to a camper trailer \nImage Description: a woman sitting on the floor eating a meal'
 '\nImage Description: a cat is sitting on top of a curtain'
 '\nImage Description: a large building with a large american flag and a sign that says first'
 '\nImage Description: a street with people walking down it and a castle in the background \nImage Description: people walking down a street with buildings reflected in a puddle \nImage Description: the cathedral of seville, spain'
 '\nImage Description: black and white photograph of trees in the forest'
 '\nImage Description: a figurine of an old man holding birds'
 '\nImage Description: a stormy sky with lightning strikes over an old house'
 '\nImage Description: a hummingbird flying towards a bird feeder'
 '\nImage Description: a view of a river and mountains from a hill'
 '\nImage Description: a large statue of trump and kim jong un is being built'
 '\nImage Description: a person standing in front of a large organ'
 '\nImage Description: a dirt road winding through a valley with mountains in the background'
 '\nImage Description: a black and white photo of a hand with two fingers up'
 '\nImage Description: a waterfall in the middle of a forest with trees'
 '\nImage Description: a man in uniform holding a camera \nImage Description: a man in uniform holding a camera and walking down the street'
 '\nImage Description: the tomb of john edward morris in the church of st john the divine \nImage Description: a large stone with a cross on it in a room'
 '\nImage Description: ferris wheel black and white'
 '\nImage Description: the apprentice mad libs book'
 '\nImage Description: a bee on a purple flower with a yellow center'
 '\nImage Description: a tractor is working in a field at sunset'
 '\nImage Description: a painting of a city with a plane flying over it'
 '\nImage Description: an empty parking garage with no cars in it'
 '\nImage Description: two blue jays perched on a metal pole'
 '\nImage Description: a man in a hospital gown holding a baby'
 '\nImage Description: a forest with trees and grass in the middle'
 '\nImage Description: a pair of shoes and a pair of jeans are on the ground'
 '\nImage Description: a black and white photo of a car parked in a parking lot \nImage Description: a white car with headlights on in a parking lot \nImage Description: a black and white photo of a car parked in a parking lot \nImage Description: a white porsche parked in a parking lot at night \nImage Description: a white car is parked in a parking lot at night'
 '\nImage Description: two men in suits sitting next to each other'
 '\nImage Description: a beach with grass and water on the shore'
 '\nImage Description: a man riding a horse in front of a herd of dogs'
 '\nImage Description: a rainbow is seen in the sky'
 '\nImage Description: the sun is shining brightly in the sky'
 '\nImage Description: a foggy morning in the city with a tall building in the background'
 '\nImage Description: a white mushroom growing in a mulch bed'
 '\nImage Description: president donald trump is seen peering out of a doorway'
 '\nImage Description: a gas station with a video screen on the machine'
 '\nImage Description: an abandoned building with concrete stairs and a concrete floor \nImage Description: a cat sitting on a wall in a building'
 '\nImage Description: a train bridge over a wooded area with trees and fog \nImage Description: the view from the top of the bridge \nImage Description: an aerial view of a train track in the woods \nImage Description: a train is on a bridge over a river \nImage Description: a train is on the tracks in the woods \nImage Description: a train is crossing a bridge over a forest'
 '\nImage Description: the beach and tropical island in the middle of the ocean'
 '\nImage Description: a candle is lit in front of a window with a lightning bolt'
 '\nImage Description: a hand holding a pendant with a blue and gold stone'
 '\nImage Description: brooklyn bridge, new york city, new york, usa'
 '\nImage Description: a man in uniform holding a pair of crutches'
 '\nImage Description: a group of people standing on a street with a fire truck \nImage Description: a street with trash and debris on it'
 '\nImage Description: a man in a suit and tie sitting at a table'
 '\nImage Description: an old photo of a man in uniform'
 '\nImage Description: the rear end of a tesla model s'
 '\nImage Description: a framed photo of a young man in a sailor uniform'
 '\nImage Description: a fire exit sign is displayed on a door'
 '\nImage Description: an old photo of cars and pedestrians on a busy city street'
 '\nImage Description: a man in uniform standing in front of a truck'
 '\nImage Description: a view of a city and a lake with a boat'
 '\nImage Description: a street with traffic at sunset'
 '\nImage Description: a bird bath in a garden with a tree in the background'
 '\nImage Description: a drawing of a hand with fingers up \nImage Description: a hand with a finger on it \nImage Description: a hand with a finger on it is shown in a black and white drawing'
 '\nImage Description: a large group of colorful balloons in the sky'
 '\nImage Description: an old photo of a man in a sailor uniform'
 '\nImage Description: an aerial view of icebergs floating in the ocean'
 '\nImage Description: a long hallway with a lot of windows and lights'
 '\nImage Description: a flag draped over a casket in a cemetery \nImage Description: a soldier in uniform playing the trumpet at a cemetery'
 '\nImage Description: the view from the top of the cliff overlooking the ocean'
 '\nImage Description: a group of men in uniform posing in front of an airplane'
 '\nImage Description: a group of six different colored bills with different designs'
 '\nImage Description: vintage photo of couple in winter clothes'
 "\nImage Description: a man in a pilot's helmet is giving a thumbs up"
 '\nImage Description: a painting of a girl with glasses and a hat flying through the air'
 '\nImage Description: a photo of a young man in a military uniform'
 '\nImage Description: a yellow and black butterfly on purple flowers'
 '\nImage Description: a man standing in a train station with the sun shining on him \nImage Description: two people walking down a street with backpacks \nImage Description: a large clock tower \nImage Description: man playing drums \nImage Description: a double decker bus \nImage Description: a street with a lot of buildings and a lot of people \nImage Description: a group of people standing in a building \nImage Description: a statue of a man sitting on a bench \nImage Description: man walking with luggage \nImage Description: a bike parked next to a door \nImage Description: a hallway with a door and a staircase \nImage Description: a bridge with a large arch \nImage Description: a man in an orange suit sitting on a bench \nImage Description: a man and woman standing in front of a food stand \nImage Description: a man is standing next to a pile of bags'
 '\nImage Description: a plant with white flowers and green leaves'
 '\nImage Description: a car is driving down the road in front of a monument'
 '\nImage Description: a painting on a easel \nImage Description: a person holding a paintbrush and a blue paintbrush in front of a river'
 '\nImage Description: a caterpillar on a brick wall'
 '\nImage Description: a puddle of water on the ground with trees reflected in it'
 '\nImage Description: a bunch of white lilies in a pot \nImage Description: a group of white flowers in front of a wall \nImage Description: a group of white flowers in front of a wall'
 '\nImage Description: a tree with white flowers in the grass'
 '\nImage Description: photograph - sunflower and bee by jimmy kirk'
 "\nImage Description: a man standing next to an airplane with a woman's face on it"
 '\nImage Description: a man in uniform with medals on his chest'
 '\nImage Description: a path through the woods with trees and plants'
 '\nImage Description: a painting of an eagle with a flag on top of it'
 '\nImage Description: a view of trees and sky from the ground'
 '\nImage Description: a man in uniform holding a rifle in the garden'
 '\nImage Description: a full moon is seen through the trees in the dark'
 '\nImage Description: a dirt road leads to a river and a sunset \nImage Description: a path next to a tree in a park \nImage Description: the sun sets over the river as seen from a boat \nImage Description: a view of a rice, field and a power line at sunset'
 '\nImage Description: a forest of yellow aspen trees'
 '\nImage Description: a close up of three bullets laying on the ground'
 '\nImage Description: a photo of a man in uniform and a pin'
 '\nImage Description: a light beam is shining on a shed'
 '\nImage Description: a rainbow is seen over the road in the distance'
 '\nImage Description: a dragonfly with a leaf on its back'
 '\nImage Description: the cover of the book the life of a soldier'
 '\nImage Description: an old photo of a man in uniform'
 '\nImage Description: a black and white photo of the eiffel tower with lightning'
 '\nImage Description: autumn leaves on the ground'
 '\nImage Description: a pathway lined with trees in a park'
 '\nImage Description: a man in black is being pushed by soldiers \nImage Description: a man is being detained by soldiers'
 '\nImage Description: a cloudy sky'
 '\nImage Description: a view of the lake and mountains from a mountain'
 '\nImage Description: a man in a uniform holding a rope'
 '\nImage Description: three men in uniform with a dog'
 '\nImage Description: a young man in a uniform is smiling'
 '\nImage Description: a person is standing in the water near a waterfall'
 '\nImage Description: a man in a military uniform standing in the doorway of an airplane'
 '\nImage Description: valley stream salutes sam baker'
 '\nImage Description: a narrow alleyway'
 '\nImage Description: a car is submerged in the water \nImage Description: a car is upside down in the water near a boat \nImage Description: a car is submerged in the water near boats'
 '\nImage Description: a white van parked in a parking lot'
 '\nImage Description: a dog wearing a red harness \nImage Description: man wearing a suit \nImage Description: a man in a mickey mouse costume holding a megaphone \nImage Description: a man holding a sign that says donald j trump \nImage Description: a person wearing a dinosaur costume \nImage Description: a man in a suit standing in front of a crowd \nImage Description: a man taking a picture of himself on a cell phone \nImage Description: a building with a sign that says "souvenirs of hollywood" \nImage Description: a man in a suit and bow tie is pointing at something \nImage Description: a man wearing a mask and holding a basketball \nImage Description: a man holding a sign that says the fcc touched my jimmy \nImage Description: a man taking a picture with his cell phone'
 '\nImage Description: a man kneeling next to a large painting \nImage Description: a digital painting of a black and white swirl'
 '\nImage Description: a toilet with a sign on it that says please do not flush anything else than toilet paper'
 '\nImage Description: a group of deer are running around in the field'
 '\nImage Description: a cloudy blue sky'
 '\nImage Description: a cat sitting on a stove top in a kitchen'
 '\nImage Description: a view of the city from a hillside at night'
 "\nImage Description: a man in sunglasses sitting in the driver's seat of an old jeep"
 '\nImage Description: a car driving down the road with a water tower in the background'
 '\nImage Description: a woman in a dress and broom is holding a broom'
 '\nImage Description: a sailboat is sailing in the ocean at sunset \nImage Description: a sailboat is sailing in the ocean at sunset \nImage Description: a sailboat is sailing in the ocean at sunset'
 '\nImage Description: a hand holding an orange flower with a yellow and orange flower'
 '\nImage Description: a black vase with flowers in it'
 '\nImage Description: a dog laying on a rock in the woods \nImage Description: a black dog laying in the grass \nImage Description: a german shepherd dog laying on a rock \nImage Description: a dog laying in the grass with its tongue out'
 '\nImage Description: a woman crossing the street at night \nImage Description: a building with a lot of windows \nImage Description: a man riding a bike past a store \nImage Description: a building with a red and white facade at night \nImage Description: the freight theater in san francisco'
 '\nImage Description: two men in military uniforms standing next to each other'
 '\nImage Description: a person holding up a cup of tea with the city in the background'
 "\nImage Description: a tall brick church with a clock tower \nImage Description: a tall brick church with a steeple \nImage Description: paul revere's house, boston, massachusetts \nImage Description: a tall brick building with a clock on the top"
 '\nImage Description: a black and white photo of a man in uniform'
 '\nImage Description: a store with couches and tables in it \nImage Description: a couch and table in a store'
 "\nImage Description: a pink rose with surveyors' flags on it"
 '\nImage Description: a group of men in uniform standing in front of a plane'
 '\nImage Description: a black and white photo of a man in uniform'
 '\nImage Description: a group of people standing around a dead body'
 '\nImage Description: a group of men in uniform posing for a photo'
 '\nImage Description: a poster of a woman with a red nose and a picture of a man with a red nose'
 '\nImage Description: a photo of a group of people in a room'
 '\nImage Description: a man and a little girl sitting together'
 "\nImage Description: three men in uniform sitting on a bench \nImage Description: a man in a pilot's uniform smiling"
 '\nImage Description: a group of men in military uniforms posing in front of an airplane'
 '\nImage Description: president trump signs the gold coin'
 '\nImage Description: a crane is standing in front of a building'
 '\nImage Description: a bird perched on a branch with a green leaf'
 "\nImage Description: jupiter's moon ganymede is the largest moon in the solar system"
 '\nImage Description: a rainy night with a car window with the words remember all too well'
 '\nImage Description: a bride and groom laugh together at their outdoor wedding \nImage Description: a bride and groom laugh together at their outdoor wedding'
 '\nImage Description: a photo of a group of men with autographs on it \nImage Description: a man holding a rifle and wearing a helmet \nImage Description: a man in a military uniform sitting on a jeep \nImage Description: two men in military uniforms sitting on a bench \nImage Description: a group of soldiers posing for a photo'
 '\nImage Description: a boy dressed as a knight holding a shield'
 '\nImage Description: a stuffed animal is sitting in a wooden box'
 '\nImage Description: a man in uniform standing next to a wall'
 '\nImage Description: a black cat is eating from a bowl on the floor'
 '\nImage Description: the sky is orange'
 '\nImage Description: a wrestler is being held down by another wrestler'
 '\nImage Description: a fighter jet sitting on the tarmac'
 '\nImage Description: a hot air balloon with people inside \nImage Description: a group of hot air balloons flying over a forest \nImage Description: a large red balloon \nImage Description: a large hot air balloon \nImage Description: a large group of balloons \nImage Description: three hot air balloons flying in the sky \nImage Description: a group of balloons \nImage Description: a group of hot air balloons flying in the sky \nImage Description: a colorful hot air balloon \nImage Description: three hot air balloons flying over a lake \nImage Description: a colorful hot air balloon \nImage Description: a hot air balloon with flames coming out of it'
 '\nImage Description: a purple flower with water droplets on it'
 '\nImage Description: a man holding a flag \nImage Description: a group of people standing in front of a fire \nImage Description: a group of people on a street \nImage Description: a group of people holding a flag'
 '\nImage Description: a young man in a sailor uniform \nImage Description: an old photo of a man in a sailor uniform'
 '\nImage Description: a child standing in front of a painting in an art museum'
 '\nImage Description: a bee on a flower in a garden'
 '\nImage Description: a street with cars driving on it'
 '\nImage Description: a man in a suit and tie standing in a hallway'
 '\nImage Description: a praying mantisce is sitting on a window sill'
 '\nImage Description: a view of a lake and grassy area with trees'
 '\nImage Description: a street with a yellow sign on it'
 '\nImage Description: a black and white photo of soldiers marching in formation'
 '\nImage Description: a man and woman sitting at a table with drinks'
 '\nImage Description: a billboard on the side of a road'
 '\nImage Description: please do not flush trash, paper towels, tissues, paper napkins, toilet paper, and other items'
 '\nImage Description: a vase with flowers sitting on a table'
 '\nImage Description: a black and white photo of three men in suits and ties'
 '\nImage Description: a man in uniform standing next to an airplane'
 '\nImage Description: a view of the sky with clouds and trees'
 '\nImage Description: an old photo of a man in uniform'
 "\nImage Description: an old photo of a young man in a sailor's uniform"
 '\nImage Description: a bird with wings spread'
 '\nImage Description: a baby duck laying on the grass'
 '\nImage Description: a person holding three blue sapphire stones in their hand'
 '\nImage Description: a black and white photo of four men in uniform'

✓ Merged 1 comment captions into dadjokes_comments
Merging captions for subreddit: foodhacks
✓ Merged 122 post captions into foodhacks_posts
✓ Merged 2 comment captions into foodhacks_comments
Merging captions for subreddit: unitedkingdom
✓ Merged 3 post captions into unitedkingdom_posts
✓ Merged 8 comment captions into unitedkingdom_comments
Merging captions for subreddit: RelationshipMemes
✓ Merged 480 post captions into RelationshipMemes_posts
Merging captions for subreddit: Art
✓ Merged 469 post captions into Art_posts
Merging captions for subreddit: IAmA
✓ Merged 162 post captions into IAmA_posts
✓ Merged 17 comment captions into IAmA_comments
Merging captions for subreddit: Entrepreneur
Merging captions for subreddit: space
✓ Merged 157 post captions into space_posts
✓ Merged 5 comment captions into space_comments
Merging captions for subreddit: worldnews
✓ Merged 6 comment captions into worldnews_comments
Merging captions for subreddit: indieheads
✓ Merged 23 post captions into indieheads_posts
✓ Merged 16 comment captions into indieheads_comments
Merging captions for subreddit: memes
✓ Merged 433 post captions into memes_posts
✓ Merged 1 comment captions into memes_comments
Merging captions for subreddit: backpacking
✓ Merged 119 post captions into backpacking_posts
✓ Merged 21 comment captions into backpacking_comments
Merging captions for subreddit: SkincareAddiction
✓ Merged 183 post captions into SkincareAddiction_posts
✓ Merged 12 comment captions into SkincareAddiction_comments
Merging captions for subreddit: news
✓ Merged 7 comment captions into news_comments
Merging captions for subreddit: boardgames
✓ Merged 122 post captions into boardgames_posts
✓ Merged 3 comment captions into boardgames_comments
Merging captions for subreddit: psychology
✓ Merged 1 post captions into psychology_posts
✓ Merged 2 comment captions into psychology_comments
Merging captions for subreddit: todayilearned
✓ Merged 26 comment captions into todayilearned_comments
Merging captions for subreddit: gifs

/tmp/ipykernel_54516/2090079016.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['\nImage Description: cloning a game is perfectly legal the tevis company'
 '\nImage Description: statistics in eu young people at the age of 25 years old have a higher income than you do'
 "\nImage Description: when it's not your fault but you just happened to be at the wrong place and time"
 "\nImage Description: well it's the day of the rapture again | made w/ imgflip meme maker"
 '\nImage Description: when a youtube you loved starts making brain videos | image tagged in youtube,youtube,memes | made w/ imgflip meme maker'
 "\nImage Description: two pictures of tom and jerry with the caption saying, 'my mom thinks about who keeps using all the shampoo in the bathroom"
 "\nImage Description: a cartoon character is standing in front of a green sign that says, 'christians walking to work after being wrong'"
 '\nImage Description: a group of yellow dragon heads with names on them'
 '\nImage Description: gta, gta, and gta 5 gta finally releases the full globe celebrating before what now what?'
 "\nImage Description: a man driving a car with the caption that says iphone 18 is going to launch with sim world wide next year, i can't prove it"
 '\nImage Description: paper is like ham made from trees'
 '\nImage Description: youtube the illusion of free choice'
 "\nImage Description: when the plot of the movie is good, but the actors can't act for shit"
 '\nImage Description: a cartoon of a man with a face that says, i can tell you why you are'
 '\nImage Description: you underestimate my power'
 '\nImage Description: a piece of bread with a metal pin sticking out of it'
 '\nImage Description: insurance company, facebook, and app i that that that that that that that that that that that that that that that that that that that that that'
 '\nImage Description: a man in a tuxedo is drinking wine and saying, "and i get watching and get mistake for each other"'
 "\nImage Description: a man laying on the ground with the caption that reads 'me going into hibernation after depositing my last $ 1 billion by 2032'"
 '\nImage Description: a man in a yellow jacket is holding a mushroom'
 '\nImage Description: people watching parents bring babies to horror movies and act shocked when they cry when they cry'
 '\nImage Description: a man with a face that says, when you realize the real test is to test'
 '\nImage Description: a monkey with a smile on its face and the words back in my day everything was terrible'
 '\nImage Description: i am opposite of artificial intelligence i am genuine stupidity'
 '\nImage Description: having a job and having a job | having a job and having a job | image tagged in having a job and having a job | made w/'
 '\nImage Description: a cartoon character is talking to a teacher'
 '\nImage Description: cartoon, meme, and meme how it feels that no matter how hard things go, i still got turned to al'
 '\nImage Description: a warm place to cum | girls appear to be the world | image tagged in a warm place to cum | made w/ imgflip meme maker'
 '\nImage Description: you may consume 3 tylenol but no more'
 '\nImage Description: what if the rapture happened but nobody qualified - what if the rapture happened but nobody qualified?'
 '\nImage Description: the chaos in my own life me on my way to help strangers with their problems'
 '\nImage Description: mom did you take tylenol when you were pregnant with me only the hangovers were really bad'
 '\nImage Description: when you are about to download a meme then realize you have no one to send it to'
 "\nImage Description: if we're still here does that mean the rapture happened none of us were taken - philosoraptor"
 '\nImage Description: jesus after the rapture finished and seeing no one showed up'
 '\nImage Description: me, minding my business enjoying my day my big toe poking a hole in my sock'
 '\nImage Description: two pictures of avatar avatar and the caption reads when you are about to sneeze but it goes away at the last moment'
 '\nImage Description: two pictures of a cartoon character holding a cup of coffee'
 "\nImage Description: 2022 is gonna be my year me now mum and dad i'm gonna be again"
 "\nImage Description: when the rapture is supposed to happen but it never does and you're still stuck on this planet with the religious weirdos"
 '\nImage Description: a person holding a kookaburra in their hand'
 '\nImage Description: the more complex a power system can get, the funnier it is when someone pulls out their gun'
 '\nImage Description: the breaking bad tv show is funny'
 '\nImage Description: when you see people driving on the highway at night with their headlights off'
 '\nImage Description: windows 7 was the last windows 7 was the last windows 7 was the last windows 7 was the last windows 7 was the last windows 7 was the last'
 '\nImage Description: two pictures of the same person with the caption japanese everything company'
 '\nImage Description: two cats are sitting on a couch with the caption saying, "me trying to stay calm my best friend being unhinged"'
 '\nImage Description: a bunch of birds sitting on a rope with the caption saying anyone makes a dollar government mine?'
 '\nImage Description: anime girl with pink hair and a phone'
 '\nImage Description: webmd releases new logo against tysabri'
 '\nImage Description: learn english learn english learn english learn english learn english learn english learn english learn english learn english learn english learn english learn english learn english learn english learn english'
 '\nImage Description: a monkey holding a drum set with the caption saying current year, anyone miss january 1st on the yb music'
 "\nImage Description: a pig with the caption, i turn vegetables into bacon what's your super power?"
 '\nImage Description: people rapture is coming bless the lord me what my dundas thought welcome'
 '\nImage Description: a cartoon drawing of a video game and a caption that says "stealing lightening from your hands"'
 "\nImage Description: shrap, the meme that says artificial intelligence can't replace you if you're not intelligent"
 "\nImage Description: let's have some fun let's play some minecraft min-maxing guide minecraft minecraft minecraft minecraft minecraft minecraft minecraft"
 "\nImage Description: when you're winning the argument, but then mispronounce a word"
 '\nImage Description: teacher, teacher, and meme teacher you just have to write a story for a class assignment me'
 "\nImage Description: a cartoon dog with the caption saying 'mr does something stupid also me when consequences"
 '\nImage Description: a pig with a caption that says, actain, accembs, accembs, aw screw it'
 '\nImage Description: four pictures of different planes and an airplane'
 '\nImage Description: if you get stuck in life, ask your friend for help me and my friend'
 '\nImage Description: supervillains the government in superhero media finally banning superheroes for whatever stupid reason'
 '\nImage Description: a man sitting in front of a sign that says ballet is the foot binding the west'
 '\nImage Description: two pictures of donald and a woman hugging each other'
 '\nImage Description: a man with a dog in his arms and the caption says, me watching my dog move in her sleep'
 '\nImage Description: two people walking down the street with the caption, "also my wife"'
 '\nImage Description: a bear is jumping in the air and the caption says rapture happened bears only'
 "\nImage Description: batman and robin are fighting each other with the caption saying it's not practice rule of cool"
 '\nImage Description: a crowd of people in a city with a speech bubble saying i need to pee'
 '\nImage Description: anime,<s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s><s>'
 '\nImage Description: a cartoon of a castle and a road with the words, "someone doing something really fucking stupid"'
 '\nImage Description: toaster is about to pop'
 '\nImage Description: a man with glasses and a frying pan in his hand'
 '\nImage Description: the characters in the game are in different poses'
 '\nImage Description: two pictures of the same man with glasses on'
 '\nImage Description: a man with a cigarette in his mouth and the words, "me the pharmacy looking at slidell'
 '\nImage Description: a dog wearing sunglasses and a necklace with the words dentist, you have been grinding in your sleep me appreciate that big dawg'
 '\nImage Description: marked safe from the fundamentalist rapture today'
 '\nImage Description: a computer screen with the words what my brain imagines when someone comments with nothing but a link'
 "\nImage Description: minecraft came out for kids, but they didn't know about rest"
 '\nImage Description: a wolf is sitting in the grass and saying when my wife kisses me off'
 '\nImage Description: a man is holding a sign that says scary fcc threats on 4 billion dollars later'
 '\nImage Description: how is working five days and having two off of balanced?'
 '\nImage Description: a cat walking in front of a volcano'
 '\nImage Description: today has been a day and tomorrow is going to be another day'
 '\nImage Description: two men are looking at each other with the caption how my dog looks at a random stranger'
 '\nImage Description: a hamburger with cheese, lettuce, and bacon'
 '\nImage Description: a hand holding a dog toy on the floor'
 "\nImage Description: meme - remembering your neighbor's name your dog's name"
 "\nImage Description: a dog with a caption that says when someone is crying and you don't know what to do"
 "\nImage Description: please don't call me poochie ever again"
 "\nImage Description: a cat sitting on the floor with the caption 'i'm over 20 bro my life is over it's done there's no point anymore i'm so"
 '\nImage Description: two people with the caption, your phone when you say you want to buy something'
 "\nImage Description: i'm a therapist, how do you express emotions emotions on the internet and share them with me and say lol me?"
 '\nImage Description: me after the rapture that happened today'
 '\nImage Description: a monkey with a red face and a caption that says when you aim dead center but the puss stream takes a'
 '\nImage Description: marked safe from the rapture'
 '\nImage Description: she was a fairy'
 '\nImage Description: the hobbit meme with the caption, "me browsing my old redditt posts i have no memory of this event"'
 '\nImage Description: the tv remote is 10 years old me'
 '\nImage Description: work and hard earn a wage see the latest rich get rich quick scheme'
 '\nImage Description: adhd and procrastination leaving my body when the subject is on love'
 '\nImage Description: a man is holding a shower head and a picture of a man with long hair'
 '\nImage Description: a cartoon character with the words how many chapters does deltune have now'
 '\nImage Description: google drive is private and only visible to you'
 "\nImage Description: me when i'm choosing food for my pets getting food for myself"
 "\nImage Description: when you question someone's fact they show you off on a tik tok or facebook"
 '\nImage Description: brainot youtube'
 "\nImage Description: when you're part of the group but not the conversation"
 '\nImage Description: a man with sunglasses and a microphone is talking about oil prices'
 "\nImage Description: a chip guy is holding a bag of chips and the caption reads, my therapist chip guy can't hurt you, you aren't real"
 "\nImage Description: a store with boxes of cigarettes and a sign that says if i'm smoking aids stop smoking aids aids aids aids aids aids aids aids aids aids aids aids"
 "\nImage Description: when i don't reach home on time"
 '\nImage Description: me on rapture day did not come on time after hours choose to stay back'
 '\nImage Description: two cats looking out the window with captions that say when the neighbors look inside and now they know too much'
 '\nImage Description: a screenshot of a facebook post that says time to absolutely revolutionize my living room'
 '\nImage Description: a man is standing next to a sign that says call me sick'
 '\nImage Description: if you plan on getting raptured you need to find someone to cover your shift - office space'
 '\nImage Description: early 2010s music videos be like'
 '\nImage Description: a dog is standing in front of a door with the caption, got any lube?'
 "\nImage Description: you're not making work better work pizza parties you're just making pizza worse"
 '\nImage Description: a comic book with the words cuss words and normal words on it'
 '\nImage Description: the cartoon shows the same person with different flags'
 '\nImage Description: a man is putting a bottle of liquid into a large container'
 '\nImage Description: a man sitting on a chair and a picture of him on a swing'
 "\nImage Description: the tarantula hawk wasp tarratula's tarantula hawk wasp"
 '\nImage Description: when she looks through your phone but all she can find is a scam is gdp fake?'
 "\nImage Description: waiting for today's rapture | made w/ imgflip meme maker"
 '\nImage Description: autism, autism, and autism my sister says anything autism announcement'
 '\nImage Description: therapist, so the problem is that you fall in love easily? me, yes my love'
 '\nImage Description: how to get rid of a clan name in clash of clans - how to get rid of a clan name in clash of clans'
 '\nImage Description: a child in a pizza restaurant employee who just wants the money'
 '\nImage Description: excuse me do you have a moment to talk about our lord and savior?'
 "\nImage Description: they don't know there's a fridge but there's not one in the fridge"
 '\nImage Description: subway tv ad - screenshot 4'
 '\nImage Description: elmo at mordor'
 '\nImage Description: winnie the pooh meme'
 "\nImage Description: when you spot your ex across the bar and you're hydrated and the ceo of staying your business - when you spot your ex across the"
 '\nImage Description: the cover of the album r em everybody berts'
 '\nImage Description: the game has been released and the characters are in the background'
 '\nImage Description: two pictures of the same man with the caption that says, "me enjoying a movie in the theatre that one group of boys constantly digging and talking out'
 '\nImage Description: the two pictures are the same, one is a cartoon and the other is a cartoon of a man talking on the phone'
 '\nImage Description: a cartoon character with the caption when your boss is doing illegal shit but you need your job'
 '\nImage Description: the space movie is about a man in space'
 '\nImage Description: the avengers are in a room with the words, "the spider is in my bedroom that caught the mosquito"'
 "\nImage Description: when humanity gives a shit destroying the planet as long as they're making profits"
 '\nImage Description: disney is too big to fail'
 '\nImage Description: a cartoon of a person holding a phone and a sign that says oracle'
 '\nImage Description: person and person in the same scene'
 '\nImage Description: when that person who never messages on group chat starts typing'
 '\nImage Description: cartoon when the fit imagined weak af'
 '\nImage Description: spongebob and the caption says, "Odyssey is the one who opened the wind bag"'
 '\nImage Description: a cartoon character wearing a hat with the caption, "multibillion dollar company watching poor people defend their shaky practices"'
 "\nImage Description: a man holding a toothbrush and saying when someone starts crying but you don't know what to do"
 '\nImage Description: when you are losing an argument but you suddenly remember his family details'
 '\nImage Description: an image of a cartoon character with a phone and text'
 "\nImage Description: a cartoon with text that says, 'me studying buddhism time to finally reveal what been causing my suffering the revealed the revealed the revealed the revealed"
 '\nImage Description: a woman in red shirt with the words pov of my bros taking up in rapture'
 '\nImage Description: a cartoon of a man and a woman with the words, wish to be rich and powerful'
 '\nImage Description: i iphone 7 is out youtubers in 2 days'
 '\nImage Description: a chicken with a white fluffy hair on its head'
 "\nImage Description: when i'm in a hating with no reasons competition and my opponent is a x user"
 '\nImage Description: i kinda thank you for being a disappointment'
 '\nImage Description: a man in headphones with the caption, when she asks how many ex u have but only had been pointless situations'
 '\nImage Description: when your day was abs out but your amazon order comes in'
 '\nImage Description: german/english peter spanish'
 '\nImage Description: the office door dash driver'
 "\nImage Description: a screenshot of a soccer player's profile"
 '\nImage Description: me pretending to not care so the screen loads faster'
 '\nImage Description: two pictures of a waterfall and a tree with the words "me wherever i catch a cold my whole body my nose"'
 '\nImage Description: an anime character with a necklace and a chain around his neck'
 '\nImage Description: a cartoon rabbit sitting on a throne with the caption, 1st grade me when i see a math problem with my name on it'
 '\nImage Description: a man in an orange jacket with the words decades of scientific research on life saving vaccines'
 "\nImage Description: i'm not sure if i'm more impressed by the fact that you managed to get a meme to the front page or the fact that you managed to"
 "\nImage Description: a man in a red hat with the caption, 'ya'll got any more of that rapture'"
 '\nImage Description: when you work continuously without getting proper sleep'
 "\nImage Description: a man and woman are in bed with the caption saying i bet he's thinking about other women"
 '\nImage Description: two women standing on a basketball court with the captions, your bank account your cryptos wallet'
 '\nImage Description: cartoon characters with the caption, "when he was asking too many questions"'
 '\nImage Description: a man holding a tv and saying do you have any hobbies?'
 "\nImage Description: a man with a beard and a mustache saying, 'i put at least at least at least at least at least at least at least at least at"
 '\nImage Description: a cat laying on a person\'s lap with a caption that says "when your shirt rides up a little"'
 '\nImage Description: the matrix, matrix, matrix 2, matrix 3, matrix 4, matrix 5, matrix 6, matrix 7, matrix 8, matrix 9, matrix'
 '\nImage Description: two pictures of a man in a suit and tie, one with a gun and the other with a gun'
 "\nImage Description: when i know a triangle has 3 sides but can't prove it"
 '\nImage Description: a plague doctor holding a plague mask and saying when you fall under the blanched before your wife comes'
 '\nImage Description: two men talking about the stock market'
 "\nImage Description: a man driving a car with the caption, when i'm trying to overtake the truck in front of me, but i have a clear front, but"
 '\nImage Description: a man in a suit and tie is standing in front of a crowd'
 '\nImage Description: americans who use military time europeans what the hell is military time?'
 '\nImage Description: tylenol all along | made w/ imgflip meme maker'
 '\nImage Description: a cat is sitting on a counter with a piece of toast in its mouth'
 '\nImage Description: a dog sleeping on a pillow with the caption how i sleep at night'
 '\nImage Description: two men talking about the movie they are watching'
 '\nImage Description: a normal day in forskaken'
 '\nImage Description: a man and a woman walking down the street in front of a house'
 '\nImage Description: will smith memes'
 '\nImage Description: two men in red shirts with the words what the fuck is a cold guy who wears'

✓ Merged 474 post captions into gifs_posts
✓ Merged 94 comment captions into gifs_comments
Merging captions for subreddit: Futurology
✓ Merged 1 comment captions into Futurology_comments
Merging captions for subreddit: strength_training
✓ Merged 1 comment captions into strength_training_comments
Merging captions for subreddit: funny
✓ Merged 281 post captions into funny_posts
✓ Merged 10 comment captions into funny_comments
Merging captions for subreddit: NetflixBestOf
✓ Merged 11 post captions into NetflixBestOf_posts
Merging captions for subreddit: 15minutefood
✓ Merged 374 post captions into 15minutefood_posts
✓ Merged 20 comment captions into 15minutefood_comments
Merging captions for subreddit: aww
✓ Merged 389 post captions into aww_posts
✓ Merged 112 comment captions into aww_comments
Merging captions for subreddit: Fitness
✓ Merged 13 comment captions into Fitness_comments
Merging captions for subreddit: Unexpected
✓ Merged 186 comment captions into Unexpected_comments
Merging captions for subreddit: Steam
✓ Merged 199 post captions into Steam_posts
✓ Merged 226 comment captions into Steam_comments
Merging captions for subreddit: philosophy
✓ Merged 2 comment captions into philosophy_comments
Merging captions for subreddit: BikiniBottomTwitter
✓ Merged 424 post captions into BikiniBottomTwitter_posts
✓ Merged 296 comment captions into BikiniBottomTwitter_comments
Merging captions for subreddit: gadgets
✓ Merged 20 comment captions into gadgets_comments
Merging captions for subreddit: PS5
✓ Merged 1 post captions into PS5_posts
✓ Merged 75 comment captions into PS5_comments
Merging captions for subreddit: itookapicture

/tmp/ipykernel_54516/2090079016.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['\nImage Description: a man is standing in front of a waterfall'
 '\nImage Description: lily pads in a pond with tall grasses'
 '\nImage Description: a black and white photo of a mountain and ocean'
 '\nImage Description: a dirt road in the middle of a field with a cloudy sky'
 '\nImage Description: an elephant with a leaf in its mouth'
 '\nImage Description: a black and white photo of a window with a view of a city'
 '\nImage Description: a river with a misty sky and a colorful sunset'
 '\nImage Description: a lake with mountains and clouds reflected in it'
 '\nImage Description: a large cathedral with a statue of a man'
 '\nImage Description: black and white photograph of trees in the forest'
 '\nImage Description: a person standing in front of a large organ'
 '\nImage Description: a white cat with yellow eyes sitting on the floor'
 '\nImage Description: the mountain peaks are covered with snow'
 '\nImage Description: the big ben clock tower in london, england'
 '\nImage Description: a small black puppy being held by a person'
 '\nImage Description: a tall building with a clock tower'
 '\nImage Description: a sunset over the water with grass and reeds'
 '\nImage Description: a narrow alley with a light shining on it'
 '\nImage Description: a tree with a large leaf'
 '\nImage Description: icebergs floating in the water with mountains in the background'
 '\nImage Description: a lake surrounded by green hills and a small town'
 '\nImage Description: a cloud is seen through a tree'
 '\nImage Description: a gorilla is hiding behind some leaves'
 '\nImage Description: a mountain is seen through a lens'
 '\nImage Description: a spider web is shown in the sunlight'
 '\nImage Description: a group of people walking down a street'
 '\nImage Description: black and white photograph of the empire state building'
 '\nImage Description: a deer laying on the grass in front of a building'
 '\nImage Description: a spider web that is on the ground'
 '\nImage Description: a river with a bridge'
 '\nImage Description: black and white photo of a large building'
 '\nImage Description: a tall tower with red lights on it'
 '\nImage Description: a purple sky with clouds and a street light'
 '\nImage Description: a lake with trees and clouds reflected in it'
 '\nImage Description: the sun shines through clouds in the sky'
 '\nImage Description: a black and white photo of a house on the water'
 '\nImage Description: a red and white lighthouse'
 '\nImage Description: a fox is walking along a fence'
 '\nImage Description: a pizza is being cooked in a wood fired oven'
 '\nImage Description: mailboxes on the side of the road in the desert'
 '\nImage Description: a small body of water surrounded by trees'
 '\nImage Description: a red kite flying over a mountain'
 '\nImage Description: a mountain lake with a purple sky and mountains in the background'
 '\nImage Description: a close up of a monkey with a blue nose'
 '\nImage Description: a building with windows and a clock tower'
 '\nImage Description: a close up of a fox with big eyes'
 '\nImage Description: a dog carrying an umbrella on a cobblestone street'
 '\nImage Description: the sky is cloudy'
 '\nImage Description: a squirrel is eating a banana in the grass'
 '\nImage Description: monument valley national monument, arizona'
 '\nImage Description: two birds perched on wires with clouds in the background'
 '\nImage Description: a black and purple bee on a bush with purple flowers'
 '\nImage Description: a brown and white butterfly on a green leaf'
 '\nImage Description: a book on a shelf with a window in the background'
 '\nImage Description: a toy robot is sitting in the dark with blue lights'
 '\nImage Description: a yellow towel hanging on the wall in a bathroom'
 '\nImage Description: a small wooden house in a field'
 '\nImage Description: mountain river by julie kim for stocksy stocksy'
 '\nImage Description: a mountain is reflected in the water'
 '\nImage Description: a view of a room with a window and a sky'
 '\nImage Description: a lone tree stands in a field of yellow flowers'
 "\nImage Description: the cathedral of sant'andrea in florence, italy"
 '\nImage Description: a crocodile is splashing water on its head'
 '\nImage Description: white rose in the garden'
 '\nImage Description: a man walking down a street with a large box'
 '\nImage Description: a street with a mountain in the background'
 '\nImage Description: a spider statue stands in the middle of a field'
 '\nImage Description: a woman in a red and white swimsuit'
 '\nImage Description: a lone rock in the middle of the ocean'
 '\nImage Description: a brown pelican is flying over the water'
 '\nImage Description: a traffic light is hanging from a pole'
 '\nImage Description: a group of mushrooms growing on a stump'
 '\nImage Description: a street with a traffic light and a building'
 '\nImage Description: a path that is lined with tall grass and plants'
 '\nImage Description: a pair of chairs sitting in the sun'
 '\nImage Description: raspberry jam with spoon'
 '\nImage Description: a white flower with yellow centers is in the grass'
 '\nImage Description: a large display of food'
 '\nImage Description: an aerial view of a mountain range with autumn foliage'
 '\nImage Description: a close up of a wall with many squares'
 '\nImage Description: a path through the woods at sunset'
 '\nImage Description: sky is blue with clouds'
 '\nImage Description: a city at night with tall buildings and traffic'
 '\nImage Description: a clock tower in a narrow street'
 '\nImage Description: a close up of a man with a long red hair'
 '\nImage Description: a panoramic view of a lake with trees and rocks'
 '\nImage Description: a sunset over the ocean with waves and a beach'
 '\nImage Description: a single candle is lit in the dark'
 '\nImage Description: a woman in a white dress standing in a kitchen'
 '\nImage Description: a cloudy sky'
 '\nImage Description: a mountain range'
 '\nImage Description: a clock on a building with a large window'
 '\nImage Description: old wooden boxes stacked on top of each other'
 '\nImage Description: a waterfall flowing under a bridge'
 '\nImage Description: a flock of birds flying over a marsh at sunset'
 '\nImage Description: a city street with a train'
 '\nImage Description: black and white photograph of a stone tower'
 '\nImage Description: a lake surrounded by mountains'
 '\nImage Description: the bridge is lit up at night with blue lights'
 '\nImage Description: fishing in the sun'
 '\nImage Description: a woman in a black hat and lingerie'
 '\nImage Description: a red flower is growing on a rock near a river'
 '\nImage Description: a person sitting on a rock overlooking a valley'
 '\nImage Description: a woman in a dress and broom is holding a broom'
 '\nImage Description: a tall building is seen through some bushes'
 '\nImage Description: a naked woman sitting in a theater with empty seats'
 '\nImage Description: a small bird is sitting on a red pipe'
 '\nImage Description: the ruins of machu picchu, peru'
 '\nImage Description: a plant growing out of a concrete wall'
 '\nImage Description: a beautiful young woman standing on a road in front of a cloudy sky'
 '\nImage Description: a tall building with a clock tower'
 '\nImage Description: a bar with a lamp and a lot of bottles on the shelves'
 '\nImage Description: a large body of water'
 '\nImage Description: a seagull standing on a ledge near water'
 '\nImage Description: a chair sitting on a hill overlooking a lake'
 '\nImage Description: a moss covered forest with trees and rocks'
 '\nImage Description: a flower growing in the grass'
 '\nImage Description: boats in the fog on a lake at sunrise'
 '\nImage Description: mercedes-benz 300sl roadster'
 '\nImage Description: a stone bridge over a body of water'
 '\nImage Description: a yellow wall with lights hanging from it'
 '\nImage Description: a woman in a black and white photo posing in a hallway'
 '\nImage Description: a close up of a brown and white tree'
 '\nImage Description: a seagull flying over water with a fish in its beak'
 '\nImage Description: a yellow and brown substance on the ground'
 '\nImage Description: a tree and grassy area with a sunset in the background'
 '\nImage Description: a turtle is walking on the beach near the ocean'
 '\nImage Description: a tall building with a clock tower'
 '\nImage Description: a tiger walking through the woods'
 '\nImage Description: a close up of a pelican with a long beak'
 '\nImage Description: a woman in a white dress sitting on a stage'
 '\nImage Description: tower bridge at night'
 '\nImage Description: the bay bridge at night with lights on'
 '\nImage Description: a black and white photo of a man hanging from a cross'
 '\nImage Description: a woman with orange hair and tattoos holding a knife'
 '\nImage Description: a blue lake surrounded by mountains and grass'
 '\nImage Description: a woman with tattoos and a skull mask holding a scythe'
 '\nImage Description: colorful houses line the shore of a lake'
 '\nImage Description: a bee is eating from a purple flower'
 '\nImage Description: the view from the alhambra palace in granada, spain'
 '\nImage Description: brooklyn bridge, new york city, new york, usa'
 '\nImage Description: a storm is seen over a building with a large mirror'
 '\nImage Description: a group of hot air balloons flying over a desert'
 '\nImage Description: a spinning wheel of steel wool is lit up at night'
 '\nImage Description: a hyena is sitting in the sand'
 '\nImage Description: a fire is burning in the dark with a basket on top'
 '\nImage Description: a man jumping off a rock into the ocean'
 '\nImage Description: a bird flying over the ocean'
 '\nImage Description: a woman standing in front of a window with a laptop'
 '\nImage Description: a group of people sitting on the grass near a waterfall'
 '\nImage Description: a close up of a flower with red and yellow petals'
 '\nImage Description: a woman holding a lit firework in the dark'
 '\nImage Description: a woman in a ghost costume standing under a tree'
 '\nImage Description: an aerial view of the ocean with waves'
 '\nImage Description: a view of the city from above with tall buildings'
 '\nImage Description: a hawk is standing on the grass'
 '\nImage Description: a dragonfly is perched on a plant near a body of water'
 '\nImage Description: sunset over the bay at the bayfront park in fort myers, florida'
 '\nImage Description: a black and white photo of a pelican'
 '\nImage Description: a group of purple flowers growing in a garden'
 '\nImage Description: a view of the sun setting over a river'
 '\nImage Description: a red brick wall with a window and a shadow'
 '\nImage Description: a plane flying over a runway at sunset'
 '\nImage Description: a person standing on a rocky shoreline at sunset'
 '\nImage Description: a bird is perched on a tree branch with flowers'
 '\nImage Description: the hawa mahal palace, jaipur, rajasthan, india'
 '\nImage Description: a man riding a bike down a street in the city'
 '\nImage Description: a leopard sitting in tall grass'
 '\nImage Description: a pink bunny statue is on display in a lobby'
 '\nImage Description: the mountains and lake are surrounded by trees'
 '\nImage Description: a large hot air balloon with a colorful design'
 '\nImage Description: aerial view of residential buildings in the city'
 '\nImage Description: the sun sets over the sand dunes in death valley'
 '\nImage Description: a woman wearing a hoodie and a cross necklace'
 '\nImage Description: a tall building with a clock tower'
 '\nImage Description: an aerial view of a beach and a small island'
 '\nImage Description: a man and woman standing on a dock'
 '\nImage Description: aerial view of the sun setting over a river'
 '\nImage Description: a tree with a bench in front of it'
 '\nImage Description: a hill with a fence'
 '\nImage Description: corgi and bride and groom'
 '\nImage Description: a person in a hoodie and mask standing in front of a light'
 '\nImage Description: sunset at kapalua resort, maui'
 '\nImage Description: a road with trees and sunbeams shining through the trees'
 '\nImage Description: a woman sitting on a chair in the ocean'
 '\nImage Description: an old room with a desk and a lot of debris'
 '\nImage Description: a large fire is burning in the mountains'
 '\nImage Description: a sunset over the water with trees in the background'
 '\nImage Description: a bird sitting on a roof with trees in the background'
 '\nImage Description: a field of yellow tulips with a ferris wheel in the background'
 '\nImage Description: a woman standing in front of a mirror'
 '\nImage Description: a table with a bottle of water and a cup of soap'
 '\nImage Description: a lion laying on a rock in a field'
 '\nImage Description: a black and white photo of a river with rocks'
 '\nImage Description: a woman with no shirt on laying on the floor'
 '\nImage Description: a black and white photo of two white ghosts standing in front of a waterfall'
 '\nImage Description: a man dressed in native american clothing holding a large scroll'
 '\nImage Description: a squirrel sitting on the grass next to a deer'
 '\nImage Description: a fence post with yellow flowers in the foreground'
 '\nImage Description: people walking up the stairs to a building with a sky in the background'
 '\nImage Description: a highway with cars driving on it'
 '\nImage Description: a woman reading a book in front of a bookcase'
 '\nImage Description: a white wall with an archway in the middle'
 '\nImage Description: a mountain with a house in the foreground and a mountain peak in the background'
 '\nImage Description: the milky way over the house'
 '\nImage Description: two people crossing a street in a busy city'
 '\nImage Description: a view of a basketball court from above'
 '\nImage Description: a green lizard sitting on a branch'
 '\nImage Description: a black and white photo of a telephone pole'
 '\nImage Description: a rainbow is seen in the sky'
 '\nImage Description: a person standing on the beach at sunset'
 '\nImage Description: a large ornate window with a clock on it'
 '\nImage Description: a blurry photo of a tree with a cloudy sky'
 '\nImage Description: a close up of a chair with a light shining on it'
 '\nImage Description: a path leading to a beach'
 '\nImage Description: a black and white photo of a house with a cat sitting in front of it'
 '\nImage Description: a door that is open in a dark room'
 '\nImage Description: fireworks explode over the building in front of a large building'
 '\nImage Description: a bird is perched on a ledge of a building'
 '\nImage Description: a car parked in front of a motel sign at night'
 '\nImage Description: a mountain with a river'
 '\nImage Description: a cell phone tower on top of a building'
 '\nImage Description: a moose with large horns eating some plants'
 '\nImage Description: the city of istanbul at night'
 '\nImage Description: a black and white photo of a person working in a kitchen'
 '\nImage Description: a person standing on top of a mountain with their arms outstretched'
 '\nImage Description: a bird walking on the ground'
 '\nImage Description: a lynx is sitting in the grass'
 '\nImage Description: a man in a blue shirt holding a blue toothbrush'
 '\nImage Description: a black and white photo of a bedroom with a bed and clothes'
 '\nImage Description: sunset on a gravel road with orange flowers'
 '\nImage Description: a baby monkey walking on a rock in the forest'
 '\nImage Description: a train traveling through a city'
 '\nImage Description: a long exposure photograph of a group of people'
 '\nImage Description: a street with cars and buses at sunset'
 '\nImage Description: a man wearing a hat'
 '\nImage Description: a white and brown cat sitting on the ground'
 '\nImage Description: a red house in the mountains with fog'
 '\nImage Description: a black and white photo of a tennis court'
 '\nImage Description: water droplet with brown color and a drop of water'
 '\nImage Description: a large building with a clock tower in the background'
 '\nImage Description: a cow grazing in a field with a wooden house'
 '\nImage Description: a person leaning on a wall'
 '\nImage Description: a man is standing on a street corner with a fire hydrant'
 '\nImage Description: a polar bear playing with a red toy'
 '\nImage Description: a building is reflected in the water'
 '\nImage Description: the horse is standing in the water with a dark sky'
 '\nImage Description: a woman with painted face and feathers on her head'
 '\nImage Description: a red house sits on top of a rocky cliff'
 '\nImage Description: a butterfly on a yellow flower'
 '\nImage Description: a bear is walking in the water'
 '\nImage Description: a building with graffiti on it is reflected in the water'
 '\nImage Description: the building is green'
 '\nImage Description: a small brown frog on a flower'
 '\nImage Description: a yellow and black striped road with a shadow'
 '\nImage Description: a yellow and black train'
 '\nImage Description: an echidna is walking on the grass'
 '\nImage Description: a view of a city from a high place'
 '\nImage Description: a dirt road in the desert with mountains in the background'
 '\nImage Description: a bird with wings spread out on a fence'
 '\nImage Description: a narrow alleyway with a sign that says "el parador"'
 '\nImage Description: a building with many windows at night'
 '\nImage Description: a deer stands in the mist at sunset'
 '\nImage Description: a person standing on a street with a leaf on the ground'
 '\nImage Description: a sailboat floating in the middle of a lake'
 '\nImage Description: a woman sitting at a desk in front of a lamp'
 '\nImage Description: a horseshoe crab on the beach'
 '\nImage Description: a man standing in front of a neon sign'
 '\nImage Description: a naked woman with tattoos laying on the ground'
 '\nImage Description: a sunset view through the trees'
 '\nImage Description: a tiny house in the woods'
 '\nImage Description: a deer with antlers laying down on the ground'
 '\nImage Description: a helicopter flying over the ocean with a person hanging from it'
 '\nImage Description: a large parking lot with a few cars parked in it'
 '\nImage Description: a canal with a bridge and gondola in front of buildings'
 '\nImage Description: the milky way is seen in the night sky'
 '\nImage Description: a large staircase with a red and black tiled floor'
 '\nImage Description: a gas station at night'
 '\nImage Description: people walking along a path in the fall'
 '\nImage Description: people are walking along the shore of a lake with mountains in the background'
 '\nImage Description: the treasury of petra, jordan'
 '\nImage Description: a wooden fence'
 '\nImage Description: a boat is in the fog on a lake'
 '\nImage Description: a person flying a kite in the woods'
 '\nImage Description: a woman in a fur coat sitting on a chair'
 '\nImage Description: black and white photo of a dock and a house'
 '\nImage Description: a man wearing a yellow and white headband'
 '\nImage Description: black and white photograph of stairs leading up to a street light'
 '\nImage Description: a large cathedral with a large ceiling and a lot of people'
 '\nImage Description: a hotel building with dark clouds in the background'
 '\nImage Description: a woman in a purple dress standing on a stone wall'
 '\nImage Description: cherry blossoms on the river in kyoto, japan'
 '\nImage Description: a city street with a building in the background'
 '\nImage Description: a large vase with a pattern on it'
 '\nImage Description: a cloudy sky'
 '\nImage Description: a road with orange flowers in the middle of the desert'
 '\nImage Description: a large body of water'

✓ Merged 482 post captions into itookapicture_posts
Merging captions for subreddit: HumansBeingBros
✓ Merged 32 post captions into HumansBeingBros_posts
✓ Merged 11 comment captions into HumansBeingBros_comments
Merging captions for subreddit: WatchPeopleDieInside
✓ Merged 5 post captions into WatchPeopleDieInside_posts
✓ Merged 50 comment captions into WatchPeopleDieInside_comments
Merging captions for subreddit: movies
✓ Merged 38 post captions into movies_posts
✓ Merged 5 comment captions into movies_comments
Merging captions for subreddit: AskReddit
✓ Merged 5 comment captions into AskReddit_comments
Merging captions for subreddit: MakeupAddiction
✓ Merged 227 post captions into MakeupAddiction_posts
✓ Merged 81 comment captions into MakeupAddiction_comments
Merging captions for subreddit: math
✓ Merged 51 post captions into math_posts
✓ Merged 5 comment captions into math_comments
Merging captions for subreddit: AnimalsBeingBros
✓ Merged 86 post captions into AnimalsBeingBros_posts
✓ Merged 196 comment captions into AnimalsBeingBros_comments
Merging captions for subreddit: science
✓ Merged 2 comment captions into science_comments
Merging captions for subreddit: iphone
✓ Merged 149 post captions into iphone_posts
✓ Merged 76 comment captions into iphone_comments
Merging captions for subreddit: Music
✓ Merged 1 post captions into Music_posts
✓ Merged 41 comment captions into Music_comments
Merging captions for subreddit: Survival
✓ Merged 39 post captions into Survival_posts
✓ Merged 16 comment captions into Survival_comments
Merging captions for subreddit: NintendoSwitch
✓ Merged 37 post captions into NintendoSwitch_posts
✓ Merged 38 comment captions into NintendoSwitch_comments
Merging captions for subreddit: tifu
✓ Merged 91 comment captions into tifu_comments
Merging captions for subreddit: LifeProTips
✓ Merged 53 comment captions into LifeProTips_comments
Merging captions for subreddit: facepalm
✓ Merged 420 post captions into facepalm_posts
✓ Merged 9 comment captions into facepalm_comments
Merging captions for subreddit: DIY
✓ Merged 237 post captions into DIY_posts
✓ Merged 2 comment captions into DIY_comments
Merging captions for subreddit: ExpectationVsReality
✓ Merged 473 post captions into ExpectationVsReality_posts
✓ Merged 245 comment captions into ExpectationVsReality_comments
Merging captions for subreddit: gaming
✓ Merged 120 post captions into gaming_posts
✓ Merged 16 comment captions into gaming_comments
Merging captions for subreddit: anime_irl
✓ Merged 455 post captions into anime_irl_posts
✓ Merged 971 comment captions into anime_irl_comments
Merging captions for subreddit: EarthPorn
✓ Merged 467 post captions into EarthPorn_posts
✓ Merged 18 comment captions into EarthPorn_comments
Merging captions for subreddit: GetMotivated
✓ Merged 198 post captions into GetMotivated_posts
✓ Merged 26 comment captions into GetMotivated_comments
Merging captions for subreddit: pettyrevenge
✓ Merged 5 comment captions into pettyrevenge_comments
Merging captions for subreddit: WesternU
✓ Merged 1 post captions into WesternU_posts
Merging captions for subreddit: europe
✓ Merged 81 post captions into europe_posts
✓ Merged 6 comment captions into europe_comments
Merging captions for subreddit: explainlikeimfive
✓ Merged 15 comment captions into explainlikeimfive_comments
Merging captions for subreddit: ChatGPT
✓ Merged 208 post captions into ChatGPT_posts
✓ Merged 173 comment captions into ChatGPT_comments
Merging captions for subreddit: marvelstudios
✓ Merged 271 post captions into marvelstudios_posts

✅ All captions merged successfully!

/tmp/ipykernel_54516/2090079016.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['\nImage Description: a mountain range with snow capped peaks in the distance'
 '\nImage Description: a rainbow is seen in front of a waterfall'
 '\nImage Description: a view of a lake and mountains with fog and red leaves'
 '\nImage Description: black and white photograph of trees in the forest'
 '\nImage Description: a lake with rocks and grass at sunset'
 '\nImage Description: the desert is covered with white rock formations'
 '\nImage Description: a view of the mountains and trees in the valley'
 '\nImage Description: a canyon with a road and trees in the foreground'
 '\nImage Description: a tree is in the water'
 '\nImage Description: moraine lake, banff national park, canada'
 '\nImage Description: a person standing on a sand dune with a milky way in the background'
 '\nImage Description: a mountain range with trees and snow on the ground'
 '\nImage Description: a waterfall in the woods'
 '\nImage Description: a mountain reflecting in a lake with a blue sky'
 '\nImage Description: black and white photograph of a mountain with snow on it'
 '\nImage Description: a view of a rocky hillside with colorful foliage'
 '\nImage Description: a large waterfall'
 '\nImage Description: the sun sets over the mountains in yosemite'
 '\nImage Description: a mountain range'
 '\nImage Description: a river with mist rising from the water'
 '\nImage Description: a lake with trees and clouds reflected in it'
 '\nImage Description: a lake surrounded by trees and mountains'
 '\nImage Description: a lake with trees and water at sunset'
 '\nImage Description: a mountain in the forest'
 '\nImage Description: a small pond surrounded by trees and grass'
 '\nImage Description: a panoramic view of the beach and sand dunes'
 '\nImage Description: a field of golden wheat under a stormy sky'
 '\nImage Description: a mountain with a red rock'
 '\nImage Description: a mountain peak is shown in the sky'
 '\nImage Description: the sky is cloudy'
 '\nImage Description: a view of the mountains and lake from the trail'
 '\nImage Description: photograph - glacier national park by jason kaufman'
 '\nImage Description: a view of a valley with a lake and mountains'
 '\nImage Description: bryce canyon national park, utah, usa'
 '\nImage Description: a mountain is reflected in a lake with rocks and water'
 '\nImage Description: a waterfall is shown in the forest with trees and rocks'
 '\nImage Description: an aerial view of a waterfall in the middle of a canyon'
 '\nImage Description: a snowy mountain range'
 '\nImage Description: a lake surrounded by trees and mountains'
 '\nImage Description: a mountain with a cloud'
 '\nImage Description: a beautiful sunset over a mountain lake and trees'
 '\nImage Description: crater lake, crater lake, crater lake, crater lake, crater lake, crater lake, crater lake, crater lake, crater lake, crater lake'
 '\nImage Description: a river running through a forest with trees and trees'
 '\nImage Description: an aerial view of a river in the desert'
 '\nImage Description: a forest of yellow aspen trees'
 '\nImage Description: a view of the canyon and mountains from a high point'
 '\nImage Description: a rainbow appears over the desert in this photo'
 '\nImage Description: a mountain range in the background'
 '\nImage Description: the mountains are covered with fall foliage'
 '\nImage Description: a waterfall is flowing down a mountain side'
 '\nImage Description: a rocky shore with waves crashing on it'
 '\nImage Description: the milky way over the mountains'
 '\nImage Description: the sun sets over the mountains and waterfalls'
 '\nImage Description: a view of the mountains and trees in the fall'
 '\nImage Description: a lake surrounded by mountains and trees'
 '\nImage Description: sunset over the desert at death valley national park'
 '\nImage Description: a lake with mountains in the background'
 '\nImage Description: a person riding a horse on a sand dune'
 '\nImage Description: a man standing on a beach with a surfboard'
 '\nImage Description: sunset at the top of a mountain with trees and foliage'
 '\nImage Description: a view of a mountain range with a small lake'
 '\nImage Description: a stream running through a forest with rocks and trees'
 '\nImage Description: a snowy mountain range with trees and snow'
 '\nImage Description: a river flowing through a valley surrounded by mountains'
 '\nImage Description: a river runs through a forest with trees and rocks'
 '\nImage Description: a mountain range with a clear blue sky'
 '\nImage Description: a large cliff with a body of water in the distance'
 '\nImage Description: a view of the ocean from a boat'
 '\nImage Description: sunset at the beach in goa'
 '\nImage Description: a mountain range with clouds and a valley'
 '\nImage Description: a mountain is seen in the distance at dusk'
 '\nImage Description: the mountains are in the background of a field'
 '\nImage Description: a mountain in the distance'
 '\nImage Description: a view of the cliffs in the fall'
 '\nImage Description: a large glacier is in the middle of a body of water'
 '\nImage Description: a river flowing through a rocky area with trees'
 '\nImage Description: a rocky mountain'
 '\nImage Description: a waterfall in the mountains'
 '\nImage Description: wildflowers on the coast of california'
 '\nImage Description: a lone elephant is walking across a field at sunset'
 '\nImage Description: a large waterfall with steam coming out of it'
 '\nImage Description: a mountain range with a lake and a tall rock'
 '\nImage Description: a mountain range with a blue sky'
 '\nImage Description: a view of the hills and mountains from a high point'
 '\nImage Description: a waterfall is flowing over rocks in the woods'
 '\nImage Description: a scenic view of the mountains with trees and clouds'
 '\nImage Description: the blue ridge parkway in autumn'
 '\nImage Description: a bench in the woods'
 '\nImage Description: a lake surrounded by rocks and trees on a cloudy day'
 '\nImage Description: a waterfall in the forest'
 '\nImage Description: a mountain with a cloud covered sky and a mountain peak'
 '\nImage Description: a lone tree on a hill overlooking the ocean'
 '\nImage Description: a mountain with snow on it'
 '\nImage Description: a mountain peak with a clear blue sky'
 '\nImage Description: the view from the top of the mountain'
 '\nImage Description: the mountains are covered with snow and trees'
 '\nImage Description: the moon rises over the mountains in the background'
 '\nImage Description: a waterfall is shown in the dark with blue water'
 '\nImage Description: a view of the ocean and the sand dunes at sunset'
 '\nImage Description: a glacier flowing through a valley under a cloudy sky'
 '\nImage Description: black and white photograph of mountains and water'
 '\nImage Description: the sunset over the forest from the top of a cliff'
 '\nImage Description: the view from the top of a mountain overlooking a river'
 '\nImage Description: a lake surrounded by trees and mountains'
 '\nImage Description: a river flowing through a forest'
 '\nImage Description: a mountain with trees and a mountain peak in the background'
 '\nImage Description: a stream runs through a forest with rocks and moss'
 '\nImage Description: the moon rises over the red rocks in sedona, arizona'
 '\nImage Description: mushrooms in the forest by johan van der kooij'
 '\nImage Description: a mountain reflecting in a lake'
 '\nImage Description: the aurora borealis over the mountains'
 '\nImage Description: a tree with spanish moss hanging from it'
 '\nImage Description: a river flows through a forest at sunset'
 '\nImage Description: the sun sets over the sand dunes in death valley'
 '\nImage Description: a mountain range with clouds and fog'
 '\nImage Description: a view of the mountain from inside a cave'
 '\nImage Description: the sun shines brightly on the mountains in the background'
 '\nImage Description: a colorful sunset over the ocean with rocks and water'
 '\nImage Description: the rock formations in the kimberley region of australia'
 '\nImage Description: a crescent moon is seen in the sky over a mountain range'
 '\nImage Description: a crescent moon is seen in the sky over a mountain range'
 '\nImage Description: a river flowing through a rocky area'
 '\nImage Description: a forest with tall trees and green foliage'
 '\nImage Description: a mountain is reflected in the water of a lake'
 '\nImage Description: autumn trees and leaves on the ground near a lake'
 '\nImage Description: a forest with trees and fog on a cloudy day'
 '\nImage Description: a river in the mountains'
 '\nImage Description: a mountain range'
 '\nImage Description: a field with trees and bushes and mountains in the background'
 '\nImage Description: waterfall in the jungle with lush vegetation'
 '\nImage Description: the mountains are reflected in the water at sunset'
 '\nImage Description: the sun shines brightly over a field with grass and trees'
 '\nImage Description: the sun shines through the clouds over a field'
 '\nImage Description: a large body of water with a rocky shore'
 '\nImage Description: a man on a skateboard riding up a mountain'
 '\nImage Description: autumn colors in the mountains of japan'
 '\nImage Description: the milky way over the pinnacles in pinnacles national monument'
 '\nImage Description: yellow flowers in front of a lake'
 '\nImage Description: a beautiful view of the jungle and mountains'
 '\nImage Description: the view from the top of bryce canyon'
 '\nImage Description: a beautiful view of mountains and a lake'
 '\nImage Description: a trail through the woods with a lake in the background'
 '\nImage Description: a small waterfall in the middle of a forest'
 '\nImage Description: two mountains with snow on them in the distance'
 '\nImage Description: a sandy beach with mountains and water'
 '\nImage Description: a view of a mountain with a waterfall and trees'
 '\nImage Description: a field with trees and a pond under a cloudy sky'
 '\nImage Description: a waterfall is surrounded by lush green trees'
 '\nImage Description: the sun is setting over the mountains in this photo'
 '\nImage Description: a grassy hillside with a few trees and a sky'
 '\nImage Description: the sunset over mono lake in mono lake national park'
 '\nImage Description: a clear blue sky'
 '\nImage Description: mount rainier, washington, usa, sunrise, sunrise, sunrise, sunrise, sunrise, sunrise, sunrise, sunrise, sunrise, sunrise,'
 '\nImage Description: a mountain range'
 '\nImage Description: a cloudy sky'
 '\nImage Description: icebergs in the water'
 '\nImage Description: yellowstone falls, yellowstone national park, wyoming'
 '\nImage Description: a beach with rocks and water at dusk'
 '\nImage Description: two red sand hills with a full moon in the sky'
 '\nImage Description: a tree with yellow leaves'
 '\nImage Description: a stream flows through a grassy field with rocks and water'
 '\nImage Description: a small lake with tall grass and trees'
 '\nImage Description: sunrise over the ocean from inside a cave'
 '\nImage Description: a mountain range with a lake and a mountain'
 '\nImage Description: a mountain range with trees and snow on top'
 '\nImage Description: a field of red and orange tulips'
 '\nImage Description: a view of the ocean from a cliff overlooking the ocean'
 '\nImage Description: a mountain range is reflected in a lake'
 '\nImage Description: an aerial view of a volcano in the middle of nowhere'
 '\nImage Description: a field of pink and red tulips'
 '\nImage Description: a snow covered mountain'
 '\nImage Description: the sun sets over the ocean and the water is calm'
 '\nImage Description: a waterfall in a forest'
 '\nImage Description: a field of pink and yellow tulips with mountains in the background'
 '\nImage Description: a lake with a small boat on it'
 '\nImage Description: a mountain range with trees and grass in the foreground'
 '\nImage Description: devils tower, wyoming, usa'
 '\nImage Description: a mountain in the distance'
 '\nImage Description: the sun sets over the mountains in the sierra nevada'
 '\nImage Description: the sun sets over the ocean and rocks on a beach'
 '\nImage Description: the red rocks of sedona, arizona'
 '\nImage Description: yosemite national park, california, usa, yosemite national park, yosemite national park, yosemite national park'
 '\nImage Description: black and white photograph of a mountain range'
 '\nImage Description: a mountain range is reflected in a lake'
 '\nImage Description: the grand canyon from the rim'
 '\nImage Description: the sun is setting behind a tree on the beach'
 '\nImage Description: a mountain range with a lake and trees'
 '\nImage Description: bryce canyon national park, utah'
 '\nImage Description: a lightning bolt strikes through the sky over a desert'
 '\nImage Description: a river in the middle of a forest'
 '\nImage Description: the perito moreno glacier in patagonia'
 '\nImage Description: a lake with clouds reflecting in it'
 '\nImage Description: a rainbow appears over the sand dunes in the desert'
 '\nImage Description: a small lake surrounded by rocks and grass'
 '\nImage Description: a river with rocks and trees in the background'
 '\nImage Description: a steamy waterfall on a hillside'
 '\nImage Description: a view of a tea plantation'
 '\nImage Description: a colorful sunset over the mountains with clouds and fog'
 '\nImage Description: a stormy day at the beach with waves crashing against rocks'
 '\nImage Description: a view of the mountains and clouds from a hill'
 '\nImage Description: a rainbow appears over a desert landscape'
 '\nImage Description: a group of dead trees on the beach'
 '\nImage Description: a mountain range with a lake in the middle'
 '\nImage Description: the desert is covered with white and brown rocks'
 '\nImage Description: the sun sets over the mountains in the dolomites'
 '\nImage Description: a snowy mountain with red trees in the foreground'
 '\nImage Description: a view of mountains and clouds at sunset'
 '\nImage Description: a mountain range with snow capped peaks under a cloudy sky'
 '\nImage Description: a river flowing through a cave with rocks and water'
 '\nImage Description: a waterfall is flowing down a rocky mountain'
 '\nImage Description: a rainbow over the ocean with rocks and a storm'
 '\nImage Description: a rainbow is seen over a desert with sand dunes'
 '\nImage Description: a mountain range with snow capped peaks'
 '\nImage Description: the view from the top of the cliff'
 '\nImage Description: a photo of the sun setting over a desert landscape'
 '\nImage Description: a waterfall in the middle of a forest with trees'
 '\nImage Description: sunset over the mountains in the canadian rockies'
 '\nImage Description: sunset over the ocean with rocks and grass'
 '\nImage Description: a mountain range with a waterfall and a lake'
 '\nImage Description: a puddle of water and a mountain in the background'
 '\nImage Description: a sunset over a field with trees and grass'
 '\nImage Description: a view of the mountains and trees in the fall'
 '\nImage Description: a river running through a forest with trees and mountains in the background'
 '\nImage Description: waterfalls in the mountains near the river'
 '\nImage Description: monument valley in the snow'
 '\nImage Description: the aurora borealis over the mountains'
 '\nImage Description: colorful wildflowers on a mountain top'
 '\nImage Description: a sunset over a marshy area with water'
 '\nImage Description: a waterfall in the middle of a forest'
 '\nImage Description: mountains and trees are seen in the distance'
 '\nImage Description: a mountain range'
 '\nImage Description: the sun sets over the mountains in this photo'
 '\nImage Description: a mountain with clouds'
 '\nImage Description: a lake surrounded by mountains and trees'
 '\nImage Description: a stormy day at the grand canyon'
 '\nImage Description: a mountain with a lake in the middle'
 '\nImage Description: a mountain range is reflected in a lake at sunset'
 '\nImage Description: a waterfall in the jungle'
 '\nImage Description: a large tree in the middle of a forest'
 '\nImage Description: a person sitting on a rock'
 '\nImage Description: a river surrounded by trees and green grass'
 '\nImage Description: a river running through a forest with trees and grass'
 '\nImage Description: mount rainier at sunset'
 '\nImage Description: the ocean is crashing against the rocks at sunset'
 '\nImage Description: the cypress trees are growing in the water'
 '\nImage Description: a rock formation in the middle of a rocky landscape'
 '\nImage Description: a waterfall surrounded by trees and fall foliage'
 '\nImage Description: a trail in the woods with lots of leaves'
 '\nImage Description: haystack rock, cannon beach, oregon'
 '\nImage Description: a mountain with a blue sky in the background'
 '\nImage Description: a mountain range with a lake and mountains in the background'
 '\nImage Description: a cloudy sky'
 '\nImage Description: a boat is in the water near a mountain'
 '\nImage Description: the ocean and rocky cliffs are surrounded by trees'
 '\nImage Description: an aerial view of a pond surrounded by green vegetation'
 '\nImage Description: waterfall in oregon'
 '\nImage Description: monument valley at sunset'
 '\nImage Description: a rocky mountain range'
 '\nImage Description: a river flowing through a forest with a mountain in the background'
 '\nImage Description: a mountain range'
 '\nImage Description: a mountain range'
 '\nImage Description: a trail in the mountains with trees and sun'
 '\nImage Description: milky way over monument valley'
 '\nImage Description: a rocky coastline with waves crashing against it'
 '\nImage Description: a beautiful sunset over a lake with water lillies'
 '\nImage Description: a river flowing through a canyon with red rocks'
 '\nImage Description: a mountain range with trees and clouds'
 '\nImage Description: a beautiful sunset over the ocean with clouds and grass'
 '\nImage Description: a large body of water'
 '\nImage Description: a river flowing through a forest with trees and rocks'
 '\nImage Description: the rock formations in the desert are very tall'
 '\nImage Description: a dirt road in the middle of a field'
 '\nImage Description: green algae on rocks at the beach'
 '\nImage Description: a view of the lake and mountains from a rocky hill'
 '\nImage Description: photograph - the rock formations of the kiwi valley by james mccormick'
 '\nImage Description: waterfall in the mountains of vietnam'
 '\nImage Description: a mountain peak with snow on it'
 '\nImage Description: sunbeams shining through clouds over mountains'
 '\nImage Description: a beautiful landscape with mountains and grass'
 '\nImage Description: sunset at the beach with clouds reflecting in the water'
 '\nImage Description: the sun is setting over a mountain range with orange flames'
 '\nImage Description: a mountain range in the background'
 '\nImage Description: the sun sets over a field of grass and trees'
 '\nImage Description: a view of a mountain range with a road and trees'
 '\nImage Description: the mountains of the sierra de la montaña in spain'
 '\nImage Description: a mountain reflecting in a lake with grass and grass'
 '\nImage Description: a waterfall is seen in the distance'
 '\nImage Description: a waterfall in the woods'
 '\nImage Description: a mountain with a pink sky and green grass'
 '\nImage Description: a view of the cliffs on the side of a mountain'
 '\nImage Description: the milky and a shooting star are seen over a canyon'
 '\nImage Description: a valley with a river and mountains under a cloudy sky'
 '\nImage Description: a tree in a field'
 '\nImage Description: a large rock formation'

In [15]:
# Save updated posts
for subreddit_name, df in datasets_posts.items():
    output_path = f"../cleaned/{subreddit_name}_posts.csv"
    df.to_csv(output_path, index=False)
    print(f"Saved: {output_path}")

# Save updated comments
for subreddit_name, df in datasets_comments.items():
    output_path = f"../cleaned/{subreddit_name}_comments.csv"
    df.to_csv(output_path, index=False)
    print(f"Saved: {output_path}")

Saved: ../cleaned/Art_posts.csv
Saved: ../cleaned/ChatGPT_posts.csv
Saved: ../cleaned/math_posts.csv
Saved: ../cleaned/ThriftStoreHauls_posts.csv
Saved: ../cleaned/memes_posts.csv
Saved: ../cleaned/HistoryMemes_posts.csv
Saved: ../cleaned/unitedkingdom_posts.csv
Saved: ../cleaned/pics_posts.csv
Saved: ../cleaned/AnimalsBeingBros_posts.csv
Saved: ../cleaned/BikiniBottomTwitter_posts.csv
Saved: ../cleaned/RelationshipMemes_posts.csv
Saved: ../cleaned/NetflixBestOf_posts.csv
Saved: ../cleaned/Daytrading_posts.csv
Saved: ../cleaned/EatCheapAndHealthy_posts.csv
Saved: ../cleaned/MakeupAddiction_posts.csv
Saved: ../cleaned/mildlyinfuriating_posts.csv
Saved: ../cleaned/Survival_posts.csv
Saved: ../cleaned/strength_training_posts.csv
Saved: ../cleaned/WatchPeopleDieInside_posts.csv
Saved: ../cleaned/Bitcoin_posts.csv
Saved: ../cleaned/pettyrevenge_posts.csv
Saved: ../cleaned/news_posts.csv
Saved: ../cleaned/indieheads_posts.csv
Saved: ../cleaned/maybemaybemaybe_posts.csv
Saved: ../cleaned/ExpectationVsReality_posts.csv
Saved: ../cleaned/sports_posts.csv
Saved: ../cleaned/funny_posts.csv
Saved: ../cleaned/StockMarket_posts.csv
Saved: ../cleaned/AITAH_posts.csv
Saved: ../cleaned/itookapicture_posts.csv
Saved: ../cleaned/marvelstudios_posts.csv
Saved: ../cleaned/PS5_posts.csv
Saved: ../cleaned/worldnews_posts.csv
Saved: ../cleaned/15minutefood_posts.csv
Saved: ../cleaned/Steam_posts.csv
Saved: ../cleaned/Fitness_posts.csv
Saved: ../cleaned/Futurology_posts.csv
Saved: ../cleaned/aww_posts.csv
Saved: ../cleaned/gifs_posts.csv
Saved: ../cleaned/NintendoSwitch_posts.csv
Saved: ../cleaned/MadeMeSmile_posts.csv
Saved: ../cleaned/careerguidance_posts.csv
Saved: ../cleaned/videos_posts.csv
Saved: ../cleaned/cars_posts.csv
Saved: ../cleaned/WesternU_posts.csv
Saved: ../cleaned/space_posts.csv
Saved: ../cleaned/gaming_posts.csv
Saved: ../cleaned/facepalm_posts.csv
Saved: ../cleaned/HumansBeingBros_posts.csv
Saved: ../cleaned/history_posts.csv
Saved: ../cleaned/gadgets_posts.csv
Saved: ../cleaned/Music_posts.csv
Saved: ../cleaned/LifeProTips_posts.csv
Saved: ../cleaned/AskReddit_posts.csv
Saved: ../cleaned/Jokes_posts.csv

Saved: ../cleaned/IAmA_posts.csv
Saved: ../cleaned/Entrepreneur_posts.csv
Saved: ../cleaned/tifu_posts.csv
Saved: ../cleaned/movies_posts.csv
Saved: ../cleaned/SkincareAddiction_posts.csv
Saved: ../cleaned/Unexpected_posts.csv
Saved: ../cleaned/Showerthoughts_posts.csv
Saved: ../cleaned/science_posts.csv
Saved: ../cleaned/DIY_posts.csv
Saved: ../cleaned/foodhacks_posts.csv
Saved: ../cleaned/GetMotivated_posts.csv
Saved: ../cleaned/backpacking_posts.csv
Saved: ../cleaned/todayilearned_posts.csv
Saved: ../cleaned/europe_posts.csv
Saved: ../cleaned/PremierLeague_posts.csv
Saved: ../cleaned/oddlysatisfying_posts.csv
Saved: ../cleaned/anime_irl_posts.csv
Saved: ../cleaned/dadjokes_posts.csv
Saved: ../cleaned/explainlikeimfive_posts.csv
Saved: ../cleaned/philosophy_posts.csv
Saved: ../cleaned/books_posts.csv
Saved: ../cleaned/EarthPorn_posts.csv
Saved: ../cleaned/psychology_posts.csv
Saved: ../cleaned/boardgames_posts.csv
Saved: ../cleaned/iphone_posts.csv
Saved: ../cleaned/IAmA_comments.csv
Saved: ../cleaned/ThriftStoreHauls_comments.csv
Saved: ../cleaned/space_comments.csv
Saved: ../cleaned/MadeMeSmile_comments.csv
Saved: ../cleaned/AITAH_comments.csv
Saved: ../cleaned/iphone_comments.csv
Saved: ../cleaned/science_comments.csv
Saved: ../cleaned/explainlikeimfive_comments.csv
Saved: ../cleaned/gaming_comments.csv
Saved: ../cleaned/mildlyinfuriating_comments.csv
Saved: ../cleaned/HumansBeingBros_comments.csv
Saved: ../cleaned/ExpectationVsReality_comments.csv
Saved: ../cleaned/NintendoSwitch_comments.csv
Saved: ../cleaned/BikiniBottomTwitter_comments.csv
Saved: ../cleaned/psychology_comments.csv
Saved: ../cleaned/StockMarket_comments.csv
Saved: ../cleaned/ChatGPT_comments.csv
Saved: ../cleaned/sports_comments.csv
Saved: ../cleaned/Daytrading_comments.csv
Saved: ../cleaned/europe_comments.csv
Saved: ../cleaned/PS5_comments.csv
Saved: ../cleaned/Bitcoin_comments.csv
Saved: ../cleaned/movies_comments.csv
Saved: ../cleaned/aww_comments.csv
Saved: ../cleaned/RelationshipMemes_comments.csv
Saved: ../cleaned/Jokes_comments.csv
Saved: ../cleaned/philosophy_comments.csv
Saved: ../cleaned/news_comments.csv
Saved: ../cleaned/dadjokes_comments.csv
Saved: ../cleaned/EarthPorn_comments.csv
Saved: ../cleaned/funny_comments.csv
Saved: ../cleaned/Fitness_comments.csv
Saved: ../cleaned/memes_comments.csv
Saved: ../cleaned/backpacking_comments.csv
Saved: ../cleaned/DIY_comments.csv
Saved: ../cleaned/careerguidance_comments.csv
Saved: ../cleaned/GetMotivated_comments.csv
Saved: ../cleaned/AskReddit_comments.csv
Saved: ../cleaned/gadgets_comments.csv
Saved: ../cleaned/Steam_comments.csv
Saved: ../cleaned/cars_comments.csv
Saved: ../cleaned/WatchPeopleDieInside_comments.csv
Saved: ../cleaned/HistoryMemes_comments.csv
Saved: ../cleaned/pettyrevenge_comments.csv
Saved: ../cleaned/MakeupAddiction_comments.csv
Saved: ../cleaned/books_comments.csv
Saved: ../cleaned/NetflixBestOf_comments.csv
Saved: ../cleaned/Survival_comments.csv
Saved: ../cleaned/worldnews_comments.csv
Saved: ../cleaned/15minutefood_comments.csv
Saved: ../cleaned/tifu_comments.csv
Saved: ../cleaned/maybemaybemaybe_comments.csv
Saved: ../cleaned/EatCheapAndHealthy_comments.csv
Saved: ../cleaned/Unexpected_comments.csv
Saved: ../cleaned/foodhacks_comments.csv
Saved: ../cleaned/gifs_comments.csv
Saved: ../cleaned/anime_irl_comments.csv
Saved: ../cleaned/marvelstudios_comments.csv
Saved: ../cleaned/indieheads_comments.csv
Saved: ../cleaned/facepalm_comments.csv
Saved: ../cleaned/pics_comments.csv
Saved: ../cleaned/unitedkingdom_comments.csv
Saved: ../cleaned/Futurology_comments.csv
Saved: ../cleaned/boardgames_comments.csv
Saved: ../cleaned/math_comments.csv
Saved: ../cleaned/videos_comments.csv
Saved: ../cleaned/oddlysatisfying_comments.csv
Saved: ../cleaned/history_comments.csv
Saved: ../cleaned/PremierLeague_comments.csv
Saved: ../cleaned/Entrepreneur_comments.csv
Saved: ../cleaned/AnimalsBeingBros_comments.csv
Saved: ../cleaned/WesternU_comments.csv
Saved: ../cleaned/SkincareAddiction_comments.csv
Saved: ../cleaned/strength_training_comments.csv
Saved: ../cleaned/Art_comments.csv
Saved: ../cleaned/itookapicture_comments.csv
Saved: ../cleaned/Music_comments.csv
Saved: ../cleaned/LifeProTips_comments.csv
Saved: ../cleaned/Showerthoughts_comments.csv
Saved: ../cleaned/todayilearned_comments.csv